### ISSUE TITLE
False positive: "error: Missing return statement  [return]" when returning from inside AsyncExitStack

### ISSUE THREAD

**Issue by james-johnston-thumbtack** [python/typeshed#10050]
The following code yields a false positive "missing return statement" when run with Mypy:

```
from contextlib import AsyncExitStack, nullcontext
import asyncio


async def test_stack() -> str:  # false positive on this line
    async with AsyncExitStack() as exit_stack:
        return "from exit stack"


async def test_null() -> str:
    async with nullcontext() as exit_stack:
        return "from null context"


async def do_main() -> None:
    print(await test_stack())
    print(await test_null())


asyncio.run(do_main())
```
The error is:
```
mypytest.py:5: error: Missing return statement  [return]
```

The problem does not occur with the `nullcontext`, thus I suspect an issue with typeshed stub for AsyncExitStack.  But I am not 100% convinced it is not a Mypy bug either.

Here is the mypy configuration in pyproject.toml:
```
[tool.mypy]
plugins = [
    "pydantic.mypy"
]
files = "src/**/*.py,tests/**/*.py"
strict = true
# These are additional checks not covered by strict:
disallow_any_unimported = true
enable_error_code = """\
    ignore-without-code,\
    truthy-bool,\
    truthy-iterable,\
    redundant-expr,\
    redundant-self,\
    unused-awaitable\
    """
warn_unreachable = true
```

**Comment by AlexWaygood** [comment]
This isn't a false positive, though I agree that this is a slightly annoying error to deal with sometimes.

Here's a slightly contrived example of the scenario mypy is warning about here:

```py
>>> import contextlib
>>> async def foo(num: int) -> float:
...     async with contextlib.AsyncExitStack() as stack:
...         stack.enter_context(contextlib.suppress(ZeroDivisionError))
...         return 1 / num
...
>>> import asyncio
>>> asyncio.run(foo(4))
0.25
>>> asyncio.run(foo(0)) is None
True
```

The function `foo` in this example has an incorrect type annotation. Although it looks like it returns a `float` in all circumstances, as we can see from this example, if `0` is passed into the function, it will return `None` instead. This is because one of the contexts added to the stack (`contextlib.suppress(ZeroDivisionError)`) will catch and swallow `ZeroDivisionError` exceptions, leading to the `AsyncExitStack` block being exited without the `return` statement having been properly executed if `0` is passed in. Thus, the correct annotation for this function would be `async def foo(num: int) -> float | None`. If you wanted to be sure it always returned a float, you'd have to have a second `return` statement outside the `AsyncExitStack` block.

Mypy knows that `AsyncExitStack` (and `ExitStack`) is a context manager that can sometimes swallow exceptions, because of the return annotation we give the `__aexit__` method in typeshed. It knows that (async) context managers with `__(a)exit__` methods that return `bool` (or `bool | None`) can sometimes swallow exceptions, leading to return statements inside those blocks not being executed:

https://github.com/python/typeshed/blob/7dcec5b3db887f518114486b3e4783dde244186d/stdlib/contextlib.pyi#L174-L176

Now, the reason why this error can be "slightly annoying" for `ExitStack` and `AsyncExitStack` is that there are situations (and it looks like yours is one of them) when we're creating `(Async)ExitStack` blocks, and _we_ know that none of the contexts we're adding the stack have the capacity to swallow any exceptions. Theoretically, I suppose mypy could special-case `(Async)ExitStack` so that it doesn't emit this error in situations where it can say for sure that no contexts have been added to the stack that could swallow exceptions. But that kind of special-casing feels like it would be fragile and error-prone.

In any case, there's nothing typeshed can do here, unfortunately. I believe our annotations for `AsyncExitStack` are basically correct here. I think mypy is also basically doing the right thing, but if you have any quibbles with their treatment of this snippet, you'd best take it up with the mypy maintainers on their issue tracker :)

Hope this helps!

**Comment by james-johnston-thumbtack** [comment]
@AlexWaygood thank you for the detailed explanation.  It makes sense, and I hadn't thought of that possibility!

**Comment by provinzkraut** [comment]
> In any case, there's nothing typeshed can do here, unfortunately. I believe our annotations for `AsyncExitStack` are basically correct here. 

The typing of `ExitStack` and `AsyncExitStack` slightly differ:

```python
class ExitStack(Generic[_ExitT_co], metaclass=abc.ABCMeta):
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None, /
    ) -> _ExitT_co: ...
```
to
```python
class AsyncExitStack(_BaseExitStack[_ExitT_co], metaclass=abc.ABCMeta):
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: TracebackType | None, /
    ) -> bool: ...
```

For `ExitStack`, it's possible to do 

```python
def some_fn() -> str:
  stack = contextlib.ExitStack[None]()
  with stack:
      return "foo"
``` and mypy is happy with it,

but for `AsyncExitStack`

```python
def some_fn() -> str:
  stack = contextlib.AsyncExitStack[None]()
  async with stack:
      return "foo"
``` the same does not work, as `__aexit__` is annotated as returning `bool` instead of `_ExitT_co`.

I think this slight adjustment would make handling these cases a bit more bearable :)
