### ISSUE TITLE
tkinter scrollbar set accept also str not only float

### ISSUE THREAD

**Issue by melassa** [python/typeshed#10071]
Tkinter scrollbar set() accepts also str not only float:

    def set(self, first: float, last: float) -> None: ...

should be:

    def set(self, first: float|str, last: float|str) -> None: ...

**Comment by sobolevn** [comment]
cc @Akuli

**Comment by Akuli** [comment]
Lots of things in tkinter accept strings, and in fact, any object with a reasonable `__str__()`. We should accept strings only if someone actually *wants* to pass strings to that method, and it isn't a bug.

I can think of at least one use case when it makes sense to pass strings to `set()`. If I remember correctly, tkinter calls `set()` with strings when you do the usual thing where a scrollbar scrolls another widget. You probably have some use case in mind as well, otherwise you wouldn't be making this issue.

PR welcome :)

**Comment by melassa** [comment]
Hi Akuli ( I am back), the user case you asked: to override Scrollbar set().
I must use float annotation to make Mypy happy but at run time I receive a str value. Example:

```
root = Tk()
class mysb(ttk.Scrollbar):
    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
    def set(self, first: float, last: float) -> None:
        print(type(first))
sb = mysb()
sb.pack()
ttk.Treeview(yscrollcommand=sb.set).pack()
tk.mainloop()
````
will output: "<class 'str'>"

**Comment by Paulie-Aditya** [comment]
Could I get this assigned to me ?

**Comment by AlexWaygood** [comment]
> Could I get this assigned to me ? I probably can fix this

We don't usually do assignments in typeshed, but feel free to send a PR! :)
