### ISSUE TITLE
Error on using Counter's __iadd__ and __isub__ with dict[Any, int]

### ISSUE THREAD

**Issue by tyilo** [python/typeshed#10202]
**Bug Report**

`Counter` supports updating with `+=` and `-=` using a `dict[Any, int]`, however mypy disallows this.

**To Reproduce**

```python
from collections import Counter

ctr: Counter[str] = Counter()
ctr += {"a": 2}
ctr -= {"a": 1}

print(ctr)
```

https://mypy-play.net/?mypy=master&python=3.11&gist=3b6ad9610e9a3d59d2838ae26c47903a

**Expected Behavior**

mypy shouldn't report any errors.

**Actual Behavior**

```
main.py:4: error: Argument 1 to "__iadd__" of "Counter" has incompatible type "dict[str, int]"; expected "Counter[str]"  [arg-type]
main.py:5: error: Argument 1 to "__isub__" of "Counter" has incompatible type "dict[str, int]"; expected "Counter[str]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

**Your Environment**

- Mypy version used: master branch
- Python version used: 3.11

**Comment by JelleZijlstra** [comment]
This is due to these lines:

https://github.com/python/typeshed/blob/e821090926dcb06d5b53e0a81f29508bbe3a911b/stdlib/collections/__init__.pyi#L302

Looking at the CPython implementation, we should indeed be able to broaden the allowed type for `__iadd__`: it accepts anything with `.items()`. (`__add__`, on the other hand, really does accept only other `Counter`s.) PR welcome!

**Comment by tyilo** [comment]
Thanks
