### ISSUE TITLE
Non-overlapping identity check error for typing.get_origin

### ISSUE THREAD

**Issue by eltoder** [python/typeshed#10405]
The following example produces an error in mypy --strict mode:
```python
import typing

TypeSpec = typing.Any

def is_union(spec: TypeSpec) -> bool:
    return typing.get_origin(spec) is typing.Union
```
(it does work without the type alias).
This gives:
```
$ mypy --strict t.py
t.py:6: error: Non-overlapping identity check (left operand type: "type", right operand type: "<typing special form>")  [comparison-overlap]
```
It looks like get_origin() is declared to return `type`, but it can actually return some other things, notably `Union` and `Literal`.

mypy versions 1.4.1.

**Comment by JelleZijlstra** [comment]
We already have a series of overloads for different cases, and the `type` return is only for `GenericAlias` arguments: https://github.com/python/typeshed/blob/7646d38302ab7c2d56c2620ac43928331cc65c98/stdlib/typing.pyi#L812

I think this might be better seen as a bug in mypy, or at least an unfortunate overload resolution.

**Comment by AlexWaygood** [comment]
> or at least an unfortunate overload resolution.

My (untested) guess would be that because `TypeSpec` is an alias for `Any`, any of the `get_origin` overloads are a valid match for the code snippet above. So mypy just blindly picks the first overload, and infers that the object returned by the `get_origin` call is an instance of `ParamSpec`.

https://github.com/python/typeshed/blob/7646d38302ab7c2d56c2620ac43928331cc65c98/stdlib/typing.pyi#L813-L814

This is indeed slightly unfortunate, but I'm not sure what we can do about it.

**Comment by eltoder** [comment]
Alright, opened a mypy bug: https://github.com/python/mypy/issues/15630

**Comment by AlexWaygood** [comment]
Going to close this, as I don't think there's anything actionable for typeshed here; this is a mypy bug
