### ISSUE TITLE
Why is the commit message not committed for a PR?

### ISSUE THREAD

**Issue by JohnVillalovos** [python/typeshed#10414]
I was wondering why the commit message is deleted when a PR is merged. The subject remains but the message has been deleted.

For example I did a PR: https://github.com/python/typeshed/pull/10407 which had a commit message. But when it was merged the commit message is now gone.

The downside to this seems like the project is very tied to GitHub as the only way to see the message of the commit is to go to GitHub and look up the PR.

**Comment by JelleZijlstra** [comment]
It's up to the person merging the PR. Personally I do try to preserve the message if the author has put in a detailed commit message, but GitHub's interface doesn't always make that easy.

**Comment by JohnVillalovos** [comment]
Thanks for the info. Is there anything I can do to make things easier when I create a PR?

It seemed like the PR had the commit modified to put the GitHub PR number in the subject. Would it help if I did that?

Anything else I can do to make it easier on the merger?

> but GitHub's interface doesn't always make that easy.

Part of the plan to keep people from migrating off of GitHub 🙂

**Comment by Akuli** [comment]
I'm used to deleting the "body" of the commit message, and leaving it as just a one-line summary that includes the PR number. Often the PR description is something like `Fixes #1234`, and the individual commit messages are one line each and many look like `* 60d4bb41 Fixed` or `* ea463b1a oops`, so that's the only reasonable option. Also, I only tend to look at one-line commit messages, and just open the PR when I want to see more details.

But this doesn't really justify deleting nicely written commit messages like yours. I will preserve them in the future :) And IMO github's UI makes this pretty easy.

> It seemed like the PR had the commit modified to put the GitHub PR number in the subject. Would it help if I did that?

Github does this automagically. You don't need to do it.
