### ISSUE TITLE
Can we add vtk stub file ?

### ISSUE THREAD

**Issue by Gryfenfer97** [python/typeshed#10442]
I am asking because the python package doesn't technically ship its stub files but allows us to generate them with a python command (see [vtkmodules/generate_pyi.py](https://docs.vtk.org/en/latest/api/python/vtkmodules/vtkmodules.generate_pyi.html))

So I don't know if it respect the third point in the requirements:
> the package does not ship with its own stubs or type annotations. 

Their module also don't generate stub files for all .py files (and in particular for `__init__.py`)

**Comment by srittau** [comment]
Thanks for working on those stubs, and just to make sure: They are of course welcome! If you have any questions or need support, please comment in your PR.

**Comment by AlexWaygood** [comment]
@Gryfenfer97, I'm closing this issue for now to keep our issue tracker tidy, since the question has been answered. But that doesn't mean that your PR isn't welcome — it is, and please continue working on it! As @srittau says, please say on the PR thread if you need any help or anything is unclear :)
