### ISSUE TITLE
TypeError: <class 'redis.client.Redis'> is not a generic class

### ISSUE THREAD

**Issue by anler** [python/typeshed#10529]
Hi, sorry in advance if this issue has anything to do with the Redis typings.

I have the following application:

```python
from redis import Redis


class App:
    def __init__(self, redis: Redis[bytes]) -> None:
        self.redis = redis


redis = Redis("localhost", 3306)
app = App(redis)
print(app)
```

and when I try to run it I'm getting:

```
python app.py
Traceback (most recent call last):
  File "/private/tmp/app/app.py", line 4, in <module>
    class App:
  File "/private/tmp/app/app.py", line 5, in App
    def __init__(self, redis: Redis[bytes]) -> None:
                              ~~~~~^^^^^^^
  File "/Users/r/.asdf/installs/python/3.11.4/lib/python3.11/typing.py", line 355, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/r/.asdf/installs/python/3.11.4/lib/python3.11/typing.py", line 1830, in __class_getitem__
    _check_generic(cls, params, len(cls.__parameters__))
  File "/Users/r/.asdf/installs/python/3.11.4/lib/python3.11/typing.py", line 281, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'redis.client.Redis'> is not a generic class
```

If I remove the generic param from `Redis` type everything works well but understandably mypy complains:

```
python -mmypy --strict .
app.py:5: error: Missing type parameters for generic type "Redis"  [type-arg]
Found 1 error in 1 file (checked 1 source file)
```

My dependencies are:
```
redis==4.6.0
types-redis==4.6.0.3
```

I have uploaded the code here: https://github.com/anler/redis-typings

Thanks in advance!

**Comment by Akuli** [comment]
The problem is that as far as Python is concerned, `Redis` is just a normal class, even though typeshed defines it as a generic class. So the `Redis[bytes]` syntax doesn't actually work when running the code in Python, even though mypy understands it as it only looks at typeshed's stub files.

You have two options:
- Use a string to annotate it: `def __init__(self, redis: "Redis[bytes]") -> None`. Mypy will understand it, Python will only see that it is a string and not bother any more with it.
- Add `from __future__ import annotations` to the beginning of the file. This basically stringifies all type annotations.

There's not much we can do about this, apart from making the class not generic which wouldn't be great.

**Comment by AlexWaygood** [comment]
There's some mypy docs on this issue here: https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

**Comment by anler** [comment]
Thanks a lot @Akuli 🙏🏻
