### ISSUE TITLE
os.waitid can return None

### ISSUE THREAD

**Issue by gotyaoi** [python/typeshed#10564]
Specifically, it can return None when its options argument contains os.WNOHANG.
>If [WNOHANG](https://docs.python.org/3/library/os.html#os.WNOHANG) is specified and there are no matching children in the requested state, None is returned.

I'm not sure there's any way to express that with overrides, given that it depends on the value of a specific argument. I'm also not sure of the ergonomic effect of making it return `os.waitid_result | None`.

**Comment by Akuli** [comment]
Since there are 5 flags that can be bitwise-ORed, there are 16 combinations of flags where `WNOHANG` is set and 16 more where it isn't set. We could add overloads with unions that have 16 members, or just return `waitid_result | Any`, similarly to how regexes work (see e.g. #10526).

I would prefer the simpler `waitid_result | Any` solution, because `os.waitid()` is not exactly the most commonly used function in the stdlib. Usually you let `subprocess.run()` or similar do the waiting or you.

**Comment by JelleZijlstra** [comment]
If it's rarely used, maybe it's better to go the more type-safe route and use `waitid_result | None` as the annotation, forcing users to think about the possibility that it may return None.

**Comment by gotyaoi** [comment]
While part of me wants it to infer the return type, a more realistic part of me thinks that being forced to check for None is fine.
