### ISSUE TITLE
typing.Any should be a class on python 3.11+

### ISSUE THREAD

**Issue by graingert** [python/typeshed#10906]
in 3.11 Any was changed from a _SpecialForm object into a class: https://github.com/python/cpython/commit/5a4973e29f2f5c4ee8c086f40325786c62381540#diff-ddb987fca5f5df0c9a2f5521ed687919d70bb3d64eaeb8021f98833a2a716887R442

**Comment by AlexWaygood** [comment]
What specific false positive errors are occurring for you as a result of it not being a class in the stub?

**Comment by graingert** [comment]
this code should typecheck correctly on 3.11+

```python
def example(t: type) -> None:
    ...

example(typing.Any)
```

**Comment by JelleZijlstra** [comment]
Any is not to be treated as a type and is heavily special-cased by type checkers. There is nothing here for typeshed to fix.

**Comment by srittau** [comment]
While, but also because it's true that `Any` is heavily special-cased, I wonder whether anything would be break if we were to bring it closer to the implementation here. While I haven't any concrete use cases in mind, and this is mostly purely hypothetical, this could help with non-type checking applications. If a change would break type checkers we shouldn't do it, but otherwise I prefer things to be closer to the implementation if possible.

**Comment by AlexWaygood** [comment]
The PR revealed that changing this would break at least pyright, and also have some impact on mypy's treatment of `Any` in some situations
