### ISSUE TITLE
Mapping methods: AbstractSet vs weaker options

### ISSUE THREAD

**Issue by dmoisset** [python/typeshed#1122]
Currently the `Mapping` protocol has its `keys()` and `items()` defined as returning an `AbstractSet`. That property holds for Python dicts, but I don't think it's infrequent to have custom Mappings that implement those as returning a list, or a generator object (it's even possible to find some of the latter in the wild within this search: https://github.com/search?utf8=%E2%9C%93&q=%22def+keys%22+%22def+items%22+yield&type=Code ). Neither of those are abstract sets (which must have a size and union/intersection/etc operations)

Something that could cover these cases is specifying those methods as just returning an `Iterable` instead. I'm aware that this would need some fixes in `Dict` (to make it covariantly redefine the results to more appropiate types) which might be messy, but it would make it easier to satisfy the protocol for custom classes in a way that is usual practice.

I'm opening this issue as a point for discussion; if a change is decided I'm willing to submit a PR, but I wanted to check that the idea mades sense.

**Comment by gvanrossum** [comment]
I think those classes are wrong though.

The code for Mapping in CPython's stdlib has docstrings stating they return sets:
```python
    def keys(self):
        "D.keys() -> a set-like object providing a view on D's keys"
        return KeysView(self)

    def items(self):
        "D.items() -> a set-like object providing a view on D's items"
        return ItemsView(self)

    def values(self):
        "D.values() -> an object providing a view on D's values"
        return ValuesView(self)
```

**Comment by KMahoney** [comment]
I ran in to an issue with this when trying to implement a class that inherits from `Mapping`. I had to implement `items` which returns a set according to its type signature, but the values I was mapping to did not implement `__hash__`, and so could not be put in to a set.

So this type signature implies that the values of your map must be hashable or comparable in some way. I'm not sure if this restriction is intentional.

**Comment by JukkaL** [comment]
@KMahoney The return type in `Mapping` is `AbstractSet`, and this doesn't require that the items are hashable. You can implement a subclass of `AbstractSet` that works with non-hashable items.

**Comment by KMahoney** [comment]
@JukkaL My thinking was it's not really technically a set if you permit duplicates, so I'd need to check either through `__hash__` or `__eq__`. I suppose in my case it's ok because the key can be compared and so the `(key, value)` tuples will always be unique.

The only thing I can think of, then, is that it might not be true for multi-maps where you can potentially have duplicate `(key, value)` pairs. I'm not sure if the `Mapping` type is intended to handle that case or if you'd use a different type for a multi-map.

**Comment by JukkaL** [comment]
`Mapping` assumes that there are no duplicate `(key, value)` pairs.

**Comment by srittau** [comment]
Returning an `AbstractSet` seems to be the correct behaviour per @gvanrossum's  comment.
