### ISSUE TITLE
Inconsistent `exportselection` type in tkinter

### ISSUE THREAD

**Issue by MarcellPerger1** [python/typeshed#11389]
The types for the `exportselection` argument in `tkinter` methods are inconsistent.  
In [7 out of the 8 occurrences](https://github.com/search?q=repo%3Apython%2Ftypeshed+exportselection+path%3Astdlib%2Ftkinter%2F__init__.pyi&type=code), the type is `bool`, but in the 1 other occurrence (in `Listbox.__init__`) the type is `int`:
https://github.com/python/typeshed/blob/9d90eeb29646f88937bcee38e4dd954a6a769ed2/stdlib/tkinter/__init__.pyi#L2113
It seems that some code passes `0` or `1` instead of a `bool` (see #4765) so it would make sense for all of these types to be `int`. Or `bool | Literal[0, 1]` is probably better.

**Comment by Akuli** [comment]
Some booleans were changed (very inconsistently) to ints in #4765.

I don't like the idea of changing more `exportselection` parameters (or other parameters) to match this. I see supporting `int` as a legacy thing that most users don't want. But because #4765 was created, I assume that someone still needs it, so we also can't just change them all to `bool`.

If you want, we can switch to using `bool | Literal[0, 1]` instead of `int`.

**Comment by Akuli** [comment]
I changed a few ints to `bool | Literal[0, 1]` in #11412. I will add more `Literal[0, 1]` into specific places when someone wants it, but I won't litter it all over tkinter for consistency.
