### ISSUE TITLE
Set up automation for updating pytype and pyright versions

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#11484]
Both pytype and pyright release pretty frequently and it's useful for us to make sure we test against the latest version. It would be nice to have a GitHub action that automatically updates them for us so we don't have to remember to make a PR. Example PRs: #11483, #11190.

I suppose other dependencies could also be auto-updated but the need isn't as great.

**Comment by AlexWaygood** [comment]
We could probably do this fairly easily with dependabot. We wouldn't need to do it with all our dependencies if we don't want to; but also, dependabot now supports setting dependency groups that are all updated together, so it wouldn't be especially noisy to do it for all our dependencies

**Comment by JelleZijlstra** [comment]
I think I'd probably want new versions of mypy, pyright, and pytype to trigger an immediate (daily) update PR, and everything else can get updated every month.

**Comment by Avasam** [comment]
I don't know if dependabot can detect our deduplicated pyright version though.
If it's automatically handled, it would be fine to have it duplicated again, but even then I'm not sure if the version given as an argument to `pyright-action` will be picked up.

**Comment by JelleZijlstra** [comment]
Sounds great, thank you! We'll review your PR soon.

**Comment by AlexWaygood** [comment]
We now have four potential solutions prototyped:
1. Carry on pinning dependencies the way we do now, and use a custom script to auto-update our dependencies: https://github.com/python/typeshed/pull/11491
2. Move our pyright pin to a `package.json` file and use dependabot to auto-update our dependencies: https://github.com/python/typeshed/pull/11564
3. Move our pyright pin to `requirements.txt` and use dependabot to auto-update our dependencies: https://github.com/python/typeshed/pull/11575
4. Carry on pinning dependencies the way we do now, and use renovate to auto-update our dependencies: https://github.com/python/typeshed/pull/11565

I think all four proposals have their pros and cons. Of the four, I like (4) best, then (3). I like (4) because:
- The configuration for renovate wasn't as complex as I feared it might be
- It looks like somebody successfully authorised renovate to run on this repository, which I was worried might be a blocker (https://github.com/python/typeshed/pull/11568)
- We can use quarterly schedules for dependencies we don't care about updating that regularly; the longest period dependabot allows is monthly
- We can have different schedules for different groups of pip dependencies; dependabot only allows us to set one schedule per ecosystem.

I have some issues with adding `pyright` to our requirements.txt file (outlined in https://github.com/python/typeshed/pull/11575#issuecomment-1988884414 / https://github.com/python/typeshed/pull/11575#issuecomment-1988985874) but I think https://github.com/python/typeshed/pull/11575 is a clear improvement over https://github.com/python/typeshed/pull/11564; it's definitely preferable to put our pyright dependency pin in one of our existing config files rather than a "fake" `package.json` file, in my opinion.

I like https://github.com/python/typeshed/pull/11491 the least out of our currently prototyped options, as I'd prefer to go with a widely used, well-tested tool rather than a custom script.

**Comment by srittau** [comment]
Personally, I like (3) best, followed by (4), if(!) the issues mentioned in #11575 can be ironed out in a non-flaky way. Adding pyright to requirements.txt has the advantage that all type checker versions are together in one file, and that users get a full test environment, just by running `pip install -r requirements.txt`.

**Comment by Avasam** [comment]
Whilst we're on the discussion, do we want to consider handling dependencies updates shared by `requirements-test.txt` and `.pre-commit-config.yaml` together? Sure there's a comment that makes it so if it's automatically updated in one file, we should remember to update it in the other file as well. But it's be nice if our final solution allows both to be handled together.

**Comment by AlexWaygood** [comment]
> Whilst we're on the discussion, do we want to consider handling dependencies updates shared by `requirements-test.txt` and `.pre-commit-config.yaml` together?

Renovate can update pre-commit config files, though there's a note in the renovate docs saying that the pre-commit maintainers don't like renovate and prefer you to use the pre-commit auto-update bots.

**Comment by JelleZijlstra** [comment]
There's a lot of things the pre-commit maintainers don't like, though it's probably worth figuring out the exact reason for the recommendation here. If Renovate works, I don't see a reason not to use it for pre-commit too.

**Comment by srittau** [comment]
Of course being able to update pre-commit as well is a big plus for renovate. In that regard, #11565 and #11575 are not mutually exclusive. The latter would work both with dependabot and renovate, but is a requisite for dependabot.

**Comment by Avasam** [comment]
The fact that we can somewhat easily achieve linked dependencies upgrade across files with Renovate, and that it seems a bit more future-proof and feature-full than Dependabot, makes me lean in its favor.

**Comment by srittau** [comment]
So it seems the best option is to go with renovate (#11565) with an option to do #11575 if we get it to work.

**Comment by AlexWaygood** [comment]
> In that regard, #11565 and #11575 are not mutually exclusive.

That hadn't occured to me, but you're quite right!

> So it seems the best option is to go with renovate (#11565) and optionally do #11575 if we get it to work.

That makes sense to me. I'll try to update that PR today so that it updates pre-commit dependencies as well.

**Comment by AlexWaygood** [comment]
We're now successfully setup with renovate 🎉:
- #11588

The only thing it looks like it won't do automatically is update our flake8-pyi pin in `.pre-commit-config.yaml` (because it's listed as an "additional dependency" of the flake8 hook rather than a hook in and of itself)
