### ISSUE TITLE
Remove paho-mqtt types (not before August 10 2024)

### ISSUE THREAD

**Issue by JonathanPlasse** [python/typeshed#11633]
Inline types were added in https://github.com/eclipse/paho.mqtt.python/commit/70cc273f173f08e2cd8b6702e1ae6ed30cfbe075.

**Comment by AlexWaygood** [comment]
Thanks! It looks like our stubsabot bot didn't mark the package as obsolete for us because a single Python file, `paho/__init__.py`, is not in a directory that is covered by a `py.typed` file. Strictly speaking that's a bug in stubsabot, but we knew the approach introduced in https://github.com/python/typeshed/pull/11053 would have false negatives from time to time.
