### ISSUE TITLE
openpyxl: no attribute "column_dimensions"

### ISSUE THREAD

**Issue by jimmyppi** [python/typeshed#11706]
Got this error after today's release:

```
error: Item "WriteOnlyWorksheet" of "Union[Union[Worksheet, WriteOnlyWorksheet, ReadOnlyWorksheet], Chartsheet]" has no attribute "column_dimensions"  [union-attr]

error: Item "ReadOnlyWorksheet" of "Union[Union[Worksheet, WriteOnlyWorksheet, ReadOnlyWorksheet], Chartsheet]" has no attribute "column_dimensions"  [union-attr]

error: Item "Chartsheet" of "Union[Union[Worksheet, WriteOnlyWorksheet, ReadOnlyWorksheet], Chartsheet]" has no attribute "column_dimensions"  [union-attr]
```

Code example:

```
import openpyxl
op = openpyxl.open(filename)
sheet = op[worksheet_name] # sheet is a WorkSheet
sheet.column_dimensions
```

**Comment by srittau** [comment]
Cc @Avasam

**Comment by Avasam** [comment]
The issue here is raised by not knowing statically whether your workbook is read_only, write_only, or "regular", and whether it contains `Chartsheet`s or not. Only `WorkSheet` contains `column_dimensions`. `Chartsheet`, `WriteOnlyWorksheet`, `ReadOnlyWorksheet` all don't.

Related to #9940 , where a generic workbook would help with knowing whether worksheets, and cells, are write_only or read_only, but that still wouldn't help with `Chartsheet`, maybe we could fudge around that one for `__getitem__` as a common use-case.
Another thing I need to validate, is whether a regular workbook could have read_only or write_only worksheets. It's "possible" code-wise, just not sure if it's an edge case that should/could happen with actual workbooks.

With the last stub update, you can do:
```py
import openpyxl
from openpyxl.worksheet.worksheet import Worksheet

workbook = openpyxl.open(filename)
sheet = workbook [worksheet_name]
assert isinstance(sheet, Worksheet)  # sheet is a Worksheet
sheet.column_dimensions
```
or
```py
import openpyxl
from openpyxl.worksheet.worksheet import Worksheet

workbook = openpyxl.open(filename)
sheet = workbook[worksheet_name]
if isinstance(sheet, Worksheet):  # sheet is a Worksheet
	sheet.column_dimensions
```

This is yet another case for https://github.com/python/typing/issues/566

That being said, with #9940 being an open issue with a potential better long-term solution (with the fudging of `Chartsheet` I have mentioned), I wouldn't mind changing the returns to `Any` (complex return type) short term. Or even back to `Worksheet`, whilst "incorrect and incomplete", getting `Worksheet` is the most common use case (and I'd just have to focus on completing #9940 :P )

**Comment by jimmyppi** [comment]
Thanks @Avasam, I'll use one of the workarounds for now
