### ISSUE TITLE
Remove types-Pillow (not before October 2024)

### ISSUE THREAD

**Issue by srittau** [python/typeshed#11759]
At this time, Pillow's type annotations are not as elaborate as typeshed's. We need to re-evaluate the type annotations in Pillow before removing the stubs.

**Comment by radarhere** [comment]
I'm not sure why October 2024 was mentioned in the title? My best guess is that it's the release of Pillow 11, when [support for Python 3.8 will be dropped](https://pillow.readthedocs.io/en/latest/installation/python-support.html)?

Pillow's type hints have become significantly better since this issue was opened. If there's anything important that you think is still missing, please let us know so that we can try and get it in before the October release.

**Comment by AlexWaygood** [comment]
> I'm not sure why October 2024 was mentioned in the title? My best guess is that it's the release of Pillow 11, when [support for Python 3.8 will be dropped](https://pillow.readthedocs.io/en/latest/installation/python-support.html)?

No, it's just our [standard policy](https://github.com/python/typeshed/blob/main/CONTRIBUTING.md#third-party-library-removal-policy) that we guarantee for users of our stubs packages.

**Comment by radarhere** [comment]
Ah, thanks for the explanation.
