### ISSUE TITLE
False positive for `shutil.rmtree` for python 3.12

### ISSUE THREAD

**Issue by wch** [python/typeshed#12103]
Consider the following file:

```python
import shutil

shutil.rmtree("abcd")
```

If I run `pyright` 1.1.366 on it, it reports an error:

```
❯ pyright --version
pyright 1.1.366
❯ pyright test.py --pythonversion 3.12
/Users/winston/temp/test.py
  /Users/winston/temp/test.py:3:8 - error: The function "rmtree" is deprecated
    The `onerror` parameter is deprecated and will be removed in Python 3.14. Use `onexc` instead. (reportDeprecated)
1 error, 0 warnings, 0 informations 
```

However, I was not able to reproduce the issue using mypy (the custom `typeshed` dir was a git clone of this repository at `main`, b3fc7e2cece78d1e81df2af0b718c1af0fd05871):

```
❯ mypy --python-version 3.12 --custom-typeshed-dir typeshed test.py
Success: no issues found in 1 source file
```

I originally filed this issue on the pyright repository (https://github.com/microsoft/pyright/issues/8087), but was told that pyright is working correctly. If that's the case, that would mean it's an issue with [shutil.pyi](https://github.com/python/typeshed/blob/b3fc7e2cece78d1e81df2af0b718c1af0fd05871/stdlib/shutil.pyi#L81
) type stub.

**Comment by AlexWaygood** [comment]
> I was not able to reproduce the issue using mypy

Pyright is producing this error because we decorate some overloads of the function with `@deprecated`. Mypy doesn't support `@deprecated` yet.

The `onerror` parameter for `rmtree` is indeed deprecated, but https://github.com/python/cpython/pull/112659 removed the deprecation warning at runtime and postponed removal of the parameter indefinitely, on the grounds that the deprecation warnings were too noisy and achieved little (see https://github.com/python/cpython/issues/112645). Given that it is still deprecated, though, maybe we should still continue to use the decorator in the stubs.

If we do keep it, though, we should apply it in a more intelligent way. Currently you don't even need to pass an argument to `onerror` for the overload we mark as deprecated to be chosen by the type checker:

https://github.com/python/typeshed/blob/b3fc7e2cece78d1e81df2af0b718c1af0fd05871/stdlib/shutil.pyi#L81

Thanks for the report! Agree there's a bug here.

**Comment by AlexWaygood** [comment]
Looks like this regression was caused by the update in https://github.com/python/typeshed/commit/50cbca413c1795bb0aeae94dee816fd90b66629b removing the first overload from `rmtree` (cc. @Avasam)
