### ISSUE TITLE
Unable to detect inherited function in highlighting or IntelliSense when using Enum member/nonmember decorators

### ISSUE THREAD

**Issue by Jacob-Friedberg** [python/typeshed#12283]
I was running into some issues with IntelliSense and highlighting in pylance: [Pylance Issue 6102](https://github.com/microsoft/pylance-release/issues/6102) 

## Minimum code example 
```python
from enum import auto, Enum, nonmember, member
import random as rand

class _Enum_helper(Enum):
    @classmethod
    #print random enum
    def random(cls):
        choice = rand.choice(list(cls))
        print(f"{choice}")

class Test():
    class A(_Enum_helper):
        FOO = auto()
        BAR = auto()

        @nonmember
        class InnerA(_Enum_helper):
            FIZZ = auto()
            BUZZ = auto()
            pass
        @member
        class InnerB(_Enum_helper):
            FUN = auto()
            BAN = auto()
            pass

        class InnerC(_Enum_helper):
            COOL= auto()
            STUFF = auto()
            pass

Test.A.random() # Has highlighting and IntelliSense auto complete.
Test.A.InnerA.random() # No highlighting or IntelliSense from inherited random
Test.A.InnerB.random() # No highlighting or IntelliSense from inherited random
Test.A.InnerC.random() # Has highlighting and IntelliSense auto-complete. acts like @member   
```
## Behavior
![image](https://github.com/python/typeshed/assets/7202146/92217bf7-b890-4e96-b5c7-49d0b9adce1b)

## Expected Behavior
I would expect inherited methods and associated named enums should be picked up under static type checking.

After chatting with erictraut he seemed to believe it had something to do typeshed definition for nonmember and member:

> This behavior is due to the way that `nonmember` and `member` are defined in the typeshed stubs. Here's the definition of `nonmember`, for example.
> 
> ```python
>     class nonmember(Generic[_EnumMemberT]):
>         value: _EnumMemberT
>         def __init__(self, value: _EnumMemberT) -> None: ...
> ```
> 
> When `@nonmember` is applied as a decorator to a class definition, it transforms that class into a `nonmember` object. This object has no method `random`, so an attempt to access this attribute will be seen as an error by a static type checker.
> 
> To fix this, the typeshed definition of `nonmember` and `member` would need to be updated. Their constructors should probably return the value they are passed.
> 
> ```python
>     class nonmember:
>         def __new__(cls, value: _EnumMemberT) -> _EnumMemberT: ...
> ```
> 
> Alternatively, a `__get__` method could be added:
> 
> ```python
>     class nonmember(Generic[_EnumMemberT]):
>         value: _EnumMemberT
>         def __init__(self, value: _EnumMemberT) -> None: ...
>         def __get__(self, instance: Any, owner: type | None = None, /) -> _EnumMemberT: ...
> ```

Any thoughts on this issue?

**Comment by Daverball** [comment]
I'm not sure I agree that this is a typeshed issue, after all `nonmember` and `member` at runtime are just simple marker classes, with neither a custom `__new__` nor are they descriptors, so lying about that, while not particularly harmful, since they'll be stripped away in classes inheriting from `Enum` or using the `EnumMeta` metaclass anyways, it's still inaccurate. It would e.g. hide bugs where they're inappropriately used in other classes.

Enums require special-casing in order to be correctly supported by type checkers, and `member`/`nonmember` are part of that special casing, since it can override the default decision of whether or not that attribute is considered a member or not. So I'm not fully convinced it's worth lying about what these marker classes are.

That being said, it might make sense to make these markers generic, simply to give type checkers more flexibility at which point the special-casing is applied, i.e. change them to:
```python
class member(Generic[_EnumMemberT]):
        value: _EnumMemberT
        def __init__(self, value: _EnumMemberT) -> None: ...

class nonmember(Generic[_EnumMemberT]):
        value: _EnumMemberT
        def __init__(self, value: _EnumMemberT) -> None: ...
```
That would allow the special casing to happen at a purely semantic level after type inference, rather than at a syntactic level.

**Comment by srittau** [comment]
I agree with @Daverball. The typeshed annotations follow the implementation exactly. This requires type checker special casing instead of typeshed hacks, although I'd be fine with making the classes generic, if that helps.
