### ISSUE TITLE
tkinter.Event is typed as generic but implementation isn't subscriptable

### ISSUE THREAD

**Issue by YodaPY** [python/typeshed#12591]
Implementation can be found here: https://github.com/python/cpython/blob/aa905925e1a0120e59e4ffe0874fbd098bf47e63/Lib/tkinter/__init__.py#L217

The stub: https://github.com/python/typeshed/blob/c54f16bdad9ea52e648a7af15e5a3b8fce362c6c/stdlib/tkinter/__init__.pyi#L241

Not sure if this is intended behaviour (I assume it isn't) but right now type checkers can only be satisfied if doing
`from __future__ import annotations`  or putting `tk.Event[...]` in quotes

**Comment by srittau** [comment]
This is a common issue with type stubs and intended. We prefer to use generics if it improves type checking even if the implementation is not generic.

**Comment by Akuli** [comment]
CPython maintainers (I think Guido) have mentioned making `tkinter.Event` generic at runtime, but they never did it.

The reason `tkinter.Event` is generic is that `tkinter.Event[tkinter.Label]` is an event coming from clicking (or otherwise interacting with) a `tkinter.Label` widget, and when you access `event.widget`, the type checker knows it is a label and acts accordingly.

**Comment by YodaPY** [comment]
Sure, once I'm free the next few days I can definitely submit a PR
