### ISSUE TITLE
basestring doesn't support any operations

### ISSUE THREAD

**Issue by ddfisher** [python/typeshed#136]
Currently the [basestring class](https://github.com/python/typeshed/blob/5be96f78d855b270b4e6fe1a3bb9dabcc62c6746/stdlib/2.7/__builtin__.pyi#L191) is empty, but it should support all operations that both `str` and `unicode` support.

**Comment by JelleZijlstra** [comment]
I'm not sure we should do this, since basestring doesn't have any methods at runtime. I suppose it's nice to use it as an annotation if you want to accept either str or unicode, but we've generally standardized on using `Union[str, unicode]` for that (or even just `unicode`, relying on mypy's implicit promotion).

**Comment by gvanrossum** [comment]
I think we should see basestring as an abstract class. So it can define methods even though they don't appear to exist at runtime, since there are no instances that aren't also instances of a concrete subclass.

**Comment by gvanrossum** [comment]
Sorry, I won't get to this.

**Comment by JelleZijlstra** [comment]
I don't think we need this any more. Python 2 is going away and we've been able to live without this for years.
