### ISSUE TITLE
Should 'type' be callable?

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#158]
Sometimes a variable's type is `type`, when the expression assigned to it is a choice between different class objects. User code sometimes wants to instantiate that type, i.e. call it. We could enable that by adding a `__call__` method to `class type` (in `builtins.pyi`). I guess its signature should allow anything since we don't know anything about the type. What should its return type be? `object` or `Any`?

Example where this would come in useful:
```
    def get_helper(manual_refund_type):
        # type: (ManualRefundType) -> ManualRefundHelper
        return {
            ManualRefundType.TAX_CREDIT: TaxManualRefundHelper,
            ManualRefundType.LEGACY_REFUND: LegacyManualRefundHelper
        }[manual_refund_type]()
```
Where `TaxManualRefundHelper` and `LegacyManualRefundHelper` are some classes.

**Comment by matthiaskramm** [comment]
Yes, that makes sense.

Return type should be `Any`, same as `eval()`.

Should said `__call__` method then take `(*args, **kwargs)`? Your example calls it without arguments, but it's probably not hard to find code where the two choices have a more complex common constructor.

**Comment by JukkaL** [comment]
The original example can be handled otherwise (https://github.com/python/mypy/issues/1437), but especially as we are planning to support types like `Type[C]`, it seems that `type` could be an alias for `Type[Any]`, and then `__call__` should take `(*args: Any, **kwargs: Any)` and return `Any`, to be consistent with `list` / `List[X]` and others.
