### ISSUE TITLE
Enum.__members__ not recognized

### ISSUE THREAD

**Issue by FichteFoll** [python/typeshed#1590]
Despite the update in #1195, I still get an error when accessing an Enum's `__members__` attribute with mypy 0.521 and Python 3.6.2:

```py
import enum


class NetworkEventName(str, enum.Enum):
    CONNECTED = "connected"
    DISCONNECTED = "disconnected"
    CLOSE_REQUEST = "close_request"
    MESSAGE = "message"
    RAW_LINE = "raw_line"


print(NetworkEventName.__members__)

```

```
> mypy /tmp/enum_test.py
/tmp/enum_test.py:12: error: Type[NetworkEventName] has no attribute "__members__"

> python /tmp/enum_test.py
OrderedDict([('CONNECTED', <NetworkEventName.CONNECTED: 'connected'>), ('DISCONNECTED', <NetworkEventName.DISCONNECTED: 'disconnected'>), ('CLOSE_REQUEST', <NetworkEventName.CLOSE_REQUEST: 'close_request'>), ('MESSAGE', <NetworkEventName.MESSAGE: 'message'>), ('RAW_LINE', <NetworkEventName.RAW_LINE: 'raw_line'>)])
```

https://github.com/python/typeshed/blob/385b9c8b660e4275fbb48765ced6a14911159782/stdlib/3.4/enum.pyi#L12-L13

**Comment by JelleZijlstra** [comment]
I wonder if this is a mypy bug, since the property is present on the metaclass in typeshed. cc @elazarg who implemented a lot of the metaclass support in mypy.

**Comment by elazarg** [comment]
It seems to happen due to a spurious "inconsistent metaclass structure".

str implements Sequence, and therefore has ABC in its MRO. This means NetworkEventName has both EnumMeta and ABCMeta in the meta-mro, neither of which is a subclass of the other. This is the pretty much same problem as with IntEnum.
It is easy to work around in mypy, but I really hope it will be possible to avoid it using Protocols. The ad-hoc special casing is not easy to do consistently and maintainably. Until then, I suggest making Enum inherit from ABCMeta if possible.
If the above suggestions are not possible, I can submit a PR to address this specific case.

**Comment by elazarg** [comment]
(so this is not a mypy bug, in my opinion)

**Comment by elazarg** [comment]
In a essence, this is duplicate of the more general python/mypy#2824

**Comment by FichteFoll** [comment]
Seems like it, indeed. I'm closing this then.

**Comment by elazarg** [comment]
Even more general: #1595.
