### ISSUE TITLE
curses: Module has no attribute "{LINES,COLS}"

### ISSUE THREAD

**Issue by ben-e-whitney** [python/typeshed#1596]
```
$ mypy --python-version 3.6 --command 'import curses; curses.LINES; curses.COLS'
<string>:1: error: Module has no attribute "LINES"
<string>:1: error: Module has no attribute "COLS"
```

I think [stdlib/3/_curses.pyi](https://github.com/python/typeshed/blob/master/stdlib/3/_curses.pyi) should annotate `LINES` and `COLS` as `int`s. [The tutorial](https://docs.python.org/3.6/howto/curses.html) doesn't specify that they're `int`s, but [the documentation](https://docs.python.org/3.6/library/curses.html) says

> This extension module is designed to match the API of ncurses, an open-source curses library hosted on Linux and the BSD variants of Unix.

and `LINES` and `COLS` appear to be declared as `int`s in `ncurses.h` (at least on the version on my system). I'm not sure about that, since the header uses a lot of macros and I'm not very familiar with C.

**Comment by ben-e-whitney** [comment]
I made a mistake with my example:

    $ python3.6 -c 'import curses; curses.LINES; curses.COLS'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    AttributeError: module 'curses' has no attribute 'LINES'

also fails. You get no error with

    $ python3.6 -c 'import curses; stdscr = curses.initscr(); curses.LINES; curses.COLS'

This doesn't solve the problem with `mypy`, though:

    mypy --python-version 3.6 --command 'import curses; stdscr = curses.initscr(); curses.LINES; curses.COLS'
    <string>:1: error: Module has no attribute "LINES"
    <string>:1: error: Module has no attribute "COLS"

[`curses.initscr`][initscr] copies `LINES` and `COLS` from `_curses` to `curses`. Would adding annotations to [stdlib/3/_curses.pyi][stub] help in this case? I am happy to make the change if so.

[initscr]: https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/curses/__init__.py#L25
[stub]: https://github.com/python/typeshed/blob/master/stdlib/3/_curses.pyi

**Comment by gossrock** [comment]
curses.LINES and curses.COLS don't exist until curses.initscr() is called.

one possible correction could be to edit curses/__init__pyi stub file to add the following lines:
```
LINES:int
COLS:int
```

Testing locally I see that with these lines added your example:

`$ mypy --python-version 3.6 --command 'import curses; stdscr = curses.initscr(); curses.LINES; curses.COLS'`

returns without errors.

but 

`$ mypy --python-version 3.6 --command 'import curses; curses.LINES; curses.COLS'`

also returns without any errors.

In this second case curses.LINES and curses.COLS will not be defined because curses.initscr() was not called. So if you run:
`$ python3.6 -c 'import curses; curses.LINES; curses.COLS'`
you get a runtime error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'curses' has no attribute 'LINES'
```

Being new to type annotation, I'm not sure if this is considered the right way to do it.

**Comment by JelleZijlstra** [comment]
Stubs can't express behavior as complex as "these module attributes only exist after a particular function is called", and it's very unlikely that we'll add support for that.

In general, I believe it's better to create false negatives (some non-working code doesn't get errors) than false positives (working code yields type errors). Therefore, we should just add the LINES and COLS to the stub. If you're interested, could you submit a PR?

**Comment by gossrock** [comment]
Would love to.
