### ISSUE TITLE
Missing bytearray.copy in Python 3

### ISSUE THREAD

**Issue by futursolo** [python/typeshed#1715]
The superclass `MutableSequence` of builtin object `bytearray` is not properly typed in the current stub file(`stdlib/3/typing.pyi`), which is missing method `clear`.

**Comment by linw1995** [comment]
and this,
error: "bytearray" has no attribute "copy"

**Comment by ExplodingCabbage** [comment]
Looks like this was resolved by https://github.com/python/typeshed/pull/1765

Possible @linw1995's issue is _not_ resolved, though?

Probably makes sense to close this and then open a separate issue for sorting out `copy`.

**Comment by JelleZijlstra** [comment]
Making changes to typeshed is easy. Could you just submit a PR adding a copy method to bytearray?

**Comment by ExplodingCabbage** [comment]
@JelleZijlstra I didn't really understand the rationale for not putting it on `MutableSequence` given that the docs state that all `MutableSequence`s should have `.copy()`. I assume this doesn't just affect `bytearray`, but I'm not sure. I don't feel comfortable that I know what the right resolution is here, but I figure that probably it involves fixing the documentation/implementation inconsistency in `collections.abc`'s `MutableSequence`, rather than hacking around it on typeshed.

**Comment by JelleZijlstra** [comment]
There does seem to be a discrepancy between the docs and the implementation, in that the MutableSequence ABC in the stdlib does not define a copy() method. Two solutions:
- Report a bug to CPython about the discrepancy, which would presumably be resolved either by changing the docs or by adding .copy() to the MutableSequence ABC (most likely only in 3.7). Then we could add .copy() to MutableSequence in typeshed, though again probably only for 3.7.
- Add the .copy() method to the stub for bytearray in typeshed. (`list`, the other prominent MutableSequence, has it already.)

**Comment by ExplodingCabbage** [comment]
Hmm, I see your rationale. Since *even if* the issue gets fixed in Python 3.7 we'd want to add `.copy()` to `bytearray` anyway to support Python <=3.7, it makes sense to add it now.

Cool, if I get a chance I'll take a look at making that PR - unless somebody else beats me to it.
