### ISSUE TITLE
sorted() and reversed() are incompatibly typed

### ISSUE THREAD

**Issue by igalic** [python/typeshed#1764]
`sorted()` returns a `List`, `reversed()` returns an `Iterator`.
Here we have two functions that are often used in the exact same context and that are typed incompatibly.

Is this an accident or on purpose?

**Comment by srittau** [comment]
There are the types the functions actually return:

```
srittau@moby:~$ python3.6
Python 3.6.3 (default, Oct  3 2017, 21:16:13) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> type(sorted([]))
<class 'list'>
>>> type(reversed([]))
<class 'list_reverseiterator'>
```

The functions should be compatible nevertheless: `sorted()` takes an `Iterable`, which `reversed()` returns, and `reversed()` expects a `Reversible`, which is a supertype of `List` that `sorted()` returns.

**Comment by gvanrossum** [comment]
This is not a question for mypy; it's more for python-list@python.org. The different types follow from the different implementations; sorting a list (without also modifying it in place) requires a new list to hold the data while it's sorted, while reversed() can be implemented as an iterator. Note that the argument types are also different: sorted() takes an iterable, but reversed() only takes sequences (since it doesn't have a buffer to store the values of an iterable before returning the last one).
