### ISSUE TITLE
Let stubs files indicate their builtin nature.

### ISSUE THREAD

**Issue by o11c** [python/typeshed#18]
Builtin modules have some differences from normal modules. For example, they do not expose `__builtins__` or `__cached__`, and don't expose `__file__` unless it comes from a shared library.

The current `builtins` vs `stdlib` distinction is not useful for checking purposes, only for stub-maintenance purposes. Though even for that purpose, it is lacking for third-party modules, and also for modules within a package (example: `lxml` is a pure-python package, but `lxml.etree` is implemented in C. I'm not sure if there are any stdlib builtin modules within a package though).

This should support the usual version and implementation checks (e.g. PyPy uses pure-python modules for many of CPython's builtin modules).

**Comment by matthiaskramm** [comment]
Originally, the main reason for the current distinction was import order: Builtin modules have priority over everything else (in other words, it's impossible to call a user module "sys"  and import it as "import sys").

However, mypy currently doesn't actually use this fact. (pytype does, but pytype doesn't have typeshed integration yet)

It's not a perfect solution. On some Linux distributions, modules that you'd expect to be builtin are compiled as an `.so` and stored in /usr/lib/python*-*/lib-dynload, in order to reduce the size of the interpreter.

**Comment by gvanrossum** [comment]
The current distinction between builtins and stdlib just continuously trips me up (since often even I forget whether a particular module is an extension or not).

I propose to drop the separate 'builtins' hierarchy and simply move its contents to 'stdlib'.

I don't think we need to have a way to indicate whether a module supports `__builtins__`, `__cached__` or `__file__` -- and even if we do we probably shouldn't use this roundabout way.

**Comment by matthiaskramm** [comment]
I'm fine with that - splitting things up was useful during auto-generation (since C extensions require quite a different approach than *.py files), but the distinction might have outlived it's usefulness.

**Comment by gvanrossum** [comment]
Let's just close this, I don't think there's much actionable here.
