### ISSUE TITLE
Python 3 HTTPConnection stubs missing class variables

### ISSUE THREAD

**Issue by scottbelden** [python/typeshed#1901]
The python 2 stubs have the class variables:

https://github.com/python/typeshed/blob/67e38b68060c9f53b0c017a4e66a1f07673c5741/stdlib/2/httplib.pyi#L40-L48

but the python 3 stubs do not:

https://github.com/python/typeshed/blob/f6b60cb3ea9ce3e7fdfcc317d9b5bbcf553c289e/stdlib/3/http/client.pyi#L127-L141

This causes a mypy error with the following:

```
error: "Type[HTTPConnection]" has no attribute "debuglevel"
```

If all that needs to be done is to add the hints for those class variables, then I don't mind making a PR to do so.

Please let me know if I should make the PR or if I have the error wrong and the problem is somewhere else.

**Comment by gvanrossum** [comment]
Hmmm... Those attributes are not documented, so I'm not sure it would be a good idea to add them to the stubs. I'm not sure why they exist in the Python 2 stubs.

This kind of question has come up a few times recently. I wonder if we need to have a general ruling on what to do with undocumented/unsupported attributes. Is it better to have mypy flag those, so you know your code is doing something fishy, or is it better to make mypy silent? There's no other tool that I know of that is capable of flagging the use of undocumented attributes, so I'm kind of leaning towards seeing this as a valuable service mypy (or rather, typeshed) provides, rather than a deficiency in the stubs. For example, if we were to add these attributes to the stubs, IDEs like PyCharm would start suggesting auto-completion for undocumented attributes, which I definitely think is a bad idea. (If there's something that's commonly used, you should petition for it to be included in the docs first.)

**Comment by scottbelden** [comment]
I like the idea of these undocumented attributes being flagged. I didn't know that `debuglevel` was undocumented, but I see that `set_debuglevel` is the proper way to do it, so I can call that instead.

As far as actual discussion on flagging vs not flagging undocumented/unsupported attibutes, perhaps that should be in a separate issue (I'm not sure if that should be in typeshed or mypy) and this should be closed.

**Comment by srittau** [comment]
It seems this problem was resolved using `set_debuglevel`. If further fields are needed, please file a separate bug report or a PR, using the `# undocumented` syntax.
