### ISSUE TITLE
email.parser has a FeedParser class in Python 2

### ISSUE THREAD

**Issue by pfmoore** [python/typeshed#1985]
The FeedParser class is missing from https://github.com/python/typeshed/blob/master/stdlib/2/email/parser.pyi, so code that uses it is being reported as in error

**Comment by JelleZijlstra** [comment]
This is a bit weird because FeedParser lives in email/feedparser.py instead of email/parser.py, and the latter merely imports it for internal use (https://github.com/python/cpython/blob/2.7/Lib/email/parser.py). However, the documentation at https://docs.python.org/2.7/library/email.parser.html#feedparser-api is under the email.parser module and talks about "email.parser.FeedParser", so I think it's reasonable to add it to the stub.

**Comment by gvanrossum** [comment]
Maybe the fact that it lives in its own module is an implementation detail?
(The docs mention it, but the phrasing makes me think that predates clear
thinking about import vs. export: "The FeedParser
<https://docs.python.org/2.7/library/email.parser.html#email.parser.FeedParser>,
imported from the email.feedparser module, [...]"
