### ISSUE TITLE
thirdparty yaml missing CLoader etc.

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#1996]
There are some optional classes in the yaml package that shadow the regular classes and behave (roughly) the same but are implemented in C; their names start with 'C'.

Here's a list:
https://github.com/yaml/pyyaml/blob/bbcf95fa051fdba9bbf879332e2f7999b195cf95/lib/yaml/cyaml.py#L2

I think we should just add these as aliases for the regular classes, e.g.
```py
CLoader = Loader
# etc.
```

**Comment by idahogray** [comment]
I would be interested in doing this work but I need just a little guidance to get started. If I understand the idea, for the CLoader example, I need to add that line above to typeshed/third_party/2and3/yaml/loader.pyi. Similarly, CDumper goes in typeshed/third_party/2and3/yaml/dumper.pyi. The remainder would follow that theme. Does that sound right?

**Comment by JelleZijlstra** [comment]
I don't think that's quite right because `CLoader` isn't in `loader.py` (https://github.com/yaml/pyyaml/blob/bbcf95fa051fdba9bbf879332e2f7999b195cf95/lib/yaml/loader.py) at runtime, but in `cyaml.py`. To match the runtime behavior, we should put it in `yaml/cyaml.pyi`, and have `from .cyaml import *` in `yaml/__init__.pyi`.
