### ISSUE TITLE
How does one become a typeshed core developer?

### ISSUE THREAD

**Issue by rchen152** [python/typeshed#2069]
Let me know if this isn't the right forum for this kind of discussion.  Is there a process for expressing interest in/working toward becoming a typeshed core developer?  Asking for the pytype team, since Matthias recently moved on to a different team.

**Comment by gvanrossum** [comment]
Hi Rebecca!

I think it's reasonable to have at least one typeshed core dev representing each project (mypy, pytype, PyCharm). So since Matthias has moved on, if the pytype team elects you, I think we should do that. (Also you've contributed plenty to typeshed so I think you already know the ropes.)

**Comment by gvanrossum** [comment]
I've invited you to become a typeshed collaborator with Write permission. Accept the invite, and enjoy!

**Comment by rchen152** [comment]
Accepted, thanks! =)
