### ISSUE TITLE
ctypes.create_unicode_buffer().value type bug

### ISSUE THREAD

**Issue by remdragon** [python/typeshed#2111]
The test script below in py2 prints out "<type 'unicode'>" but mypy --py2 reveal_type yields 'builtins.str'

The test script below in py3 prints out "<class 'str'>" but mypy reveal_type yields 'builtins.bytes'

I believe that typeshed is incorrectly reporting create_unicode_buffer().value to be of type bytes when it's supposed to be type Text.

```
import ctypes
buf = ctypes.create_unicode_buffer ( 42 )
print ( type ( buf.value ) )
```

**Comment by dgelessus** [comment]
The issue here is that the `ctypes.Array` stub doesn't declare the `value` attribute correctly for `c_wchar` arrays. Currently, the stub declares the `value` and `raw` attributes as `bytes` on all `Array`s. That works for `c_char` arrays (where `value` and `raw` are `bytes`), and sort of works for other array types (the attributes don't exist, and mypy won't error if you try to use them anyway, but correct code doesn't cause any false errors). However `c_wchar` arrays aren't handled correctly by the stub, because their `value` attribute should have type `unicode`.

Since there's no way to change the type of the `value` attribute based on `Array`'s type argument, we could change `value`'s type either to `Union[bytes, unicode]` or to `Any`. While `Union[bytes, unicode]` would be more specific, I think it would cause false errors when code correctly assumes that the `value` of a `c_char` array is always `bytes` (same for `c_wchar` and `unicode`). `Any` is less specific, but doesn't cause any false errors.

The `raw` attribute can be left as `bytes`, because it only exists for `c_char` arrays, and not `c_wchar` arrays.

Maybe the mypy plugin for `ctypes` (python/mypy#4869) could provide better information about the `value` and `raw` attributes of `Array` (i. e. give them the correct types for the arrays where they exist, and remove them for arrays where they don't exist).

**Comment by JelleZijlstra** [comment]
Thanks for the thorough discussion!

It sounds like we should just use `Any` in typeshed for now, and possibly rely on a mypy plugin to provide more thorough types later.
