### ISSUE TITLE
Argument 1 of "__lt__" incompatible with supertype "tuple"

### ISSUE THREAD

**Issue by telendt** [python/typeshed#228]
I get `error: Argument 1 of "__lt__" incompatible with supertype "tuple"` for the following code:

```
class Person(typing.NamedTuple('Person', [
        ('first_name', str),
        ('last_name', str)])):
    def __lt__(self, other: 'Person') -> bool:
        return self.last_name < other.last_name
```

**Comment by gvanrossum** [comment]
You don't even need `NamedTuple` for this. I get the same with any class derived from `tuple`:
```
class Person(tuple):
    def __lt__(self, other: 'Person') -> bool:
        return self[0] < other[0]
```
The error goes away when the type of `other` is given as `tuple`. I wonder if this is more a mypy issue than a typeshed issue? The definition of `tuple.__lt__` in `builtins.pyi` looks impeccable.

**Comment by gvanrossum** [comment]
I wasn't very clear. When overriding a method you have to be contravariant in the args. Since the base class has 'other: tuple', the subclass must accept all tuples. We can't really fix this by using a more restricted type in the definition of tuple, since tuples really do support comparisons to all tuples. We would need to change mypy (and PEP 484) to allow overriding of methods to be covariant. But that is a serious problem, since it would allow writing progams that break but type-check without errors.

Conclusion: you may be better off not subclassing NamedTuple...

**Comment by telendt** [comment]
@gvanrossum: Yes, sorry. That's more a mypy issue. I accidentally reported it here since I reported #227 shortly before.

I think I understand you explanation and I see that it's not limited to tuples.

```
class Person:
    def __init__(self, name: str) -> None:
        self.name = name

    def __lt__(self, other: 'Person') -> bool:
        return self.name < other.name

class Employee(Person):
    def __init__(self, name: str, age: int) -> None:
        super().__init__(name)
        self.age = age

    def __lt__(self, other: 'Employee') -> bool:
        return self.age < other.age
```

How could I define custom ordering in my subclass with type annotations?

**Comment by telendt** [comment]
I guess I can live with:

```
class Employee(Person):
    def __init__(self, name: str, age: int) -> None:
        super().__init__(name)
        self.age = age

    def __lt__(self, other: 'Person') -> bool:
        if isinstance(self, Employee):
            return self.age < other.age
        else:
            return super().__lt__(other)
```

Although it would be nice if `__lt__` (and other magic methods) supported single dispatch.

I'm fine with this workaround. Should I close the issue?

**Comment by gvanrossum** [comment]
I think we're not going to be able to change this so please do close the
issue.

--Guido (mobile)
