### ISSUE TITLE
Dict __init__ overload doesn't allow for List[T] 

### ISSUE THREAD

**Issue by TylerLubeck** [python/typeshed#256]
This code (where `value` is `List[str]`):
`dict(s.split('=', 1) for s in value)`

Gives this error:
`error: Generator has incompatible item type List[str]`

I spoke with @gnprice about this at Pycon 2016.

**Comment by JelleZijlstra** [comment]
This was discussed in #257 and rejected, basically because there's no way to express "`List[KeyType, ValueType]`" in the current type system. I don't think that has really changed, so I'm closing this issue.

At runtime, dict actually accepts any `Iterable[Iterable]` where the inner iterable is of length 2: for example, `dict({frozenset(['a', 'b'])})` works, although it's unspecified whether `'a'` or `'b'` will be the key.
