### ISSUE TITLE
missing stubs for multiprocessing module

### ISSUE THREAD

**Issue by radkujawa** [python/typeshed#2758]
at least multiprocessing.spawn and multiprocessing.pool.CLOSE are missing.

imports.py:
```
from multiprocessing import Manager
from multiprocessing.spawn import freeze_support
from multiprocessing.pool import CLOSE
```

got:
```
$ mypy imports.py 
imports.py:2: error: No library stub file for standard library module 'multiprocessing.spawn'
imports.py:2: note: (Stub files are from https://github.com/python/typeshed)
imports.py:3: error: Module 'multiprocessing.pool' has no attribute 'CLOSE'
$
```

so `multiprocessing.Manager` is accepted, but e.g. `multiprocessing.spawn` is not.

mypy 0.650, python 3.6

on mypy's head is the same behaviour.

**Comment by smcl** [comment]
I started looking into this because I was playing with mypy and hunted around for a first issue to tackle, but I wonder if this should be instead closed. In the three lines of the example given:

1. there is no error given for `multiprocessing.Manager`, so we needn't worry about that
2. reading the [docs](https://docs.python.org/3.7/library/multiprocessing.html) seems to suggest that people should use `from multiprocessing import freeze_support` which _does_ have a type in `multiprocessing/__init__.pyi`
3. there's no reference to `CLOSE` (or its friends `RUN` and `TERMINATE`) in the documentation, and I can't find too many references to their usage outside this file which suggests these are internal

So maybe a question for @srittau - do you think we should have types for these modules? If so I'm happy to go ahead and add them. I'd just like to double check it's the right thing to do first.

**Comment by srittau** [comment]
It's a bit of an open question: Should we follow documentation or implementation? At the moment, we tend to follow implementation in cases like this. So moving `freeze_support()` to `multiprocessing.spawn` (where it is defined in the implementation) and then re-exporting from `multiprocessing` is fine, even if the current annotations are okay as well.

While `CLOSE` et al. are not documented, they are also not documented or marked as private and obviously in use. I'd tend to include them and mark them with `# undocumented`.

**Comment by smcl** [comment]
OK makes sense, so for this one I can probably err on the side of caution (as the contributing guidelines advise) when deciding what to include, and where necessary we should favour matching the implementation does
