### ISSUE TITLE
Email example from python docs doesn't validate: Address as EmailMessage header

### ISSUE THREAD

**Issue by arjennienhuis** [python/typeshed#2863]
`EmailMessage.__setitem__` should support `Address` as a value. At least the Python docs email example think it does. See https://docs.python.org/3/library/email.examples.html

test_mypy.py:
```
from email.message import EmailMessage
from email.headerregistry import Address

msg = EmailMessage()
msg['From'] = Address("Pepé Le Pew", "pepe", "example.com")
```

And then:
```
$ mypy test_mypy.py
test_mypy.py:5: error: Incompatible types in assignment (expression has type "Address", target has type "Union[str, Header]")
```

**Comment by srittau** [comment]
True. Patches welcome!

**Comment by arjennienhuis** [comment]
I'm not sure how. Maybe:

```_HeaderType = Union[str, Header, ContentTransferEncodingHeader, ContentTypeHeader, UniqueDateHeader, SingleAddressHeader, AddressHeader, UniqueAddressHeader, UniqueSingleAddressHeader, MIMEVersionHeader, UniqueUnstructuredHeader, DateHeader, ContentDispositionHeader]```

Or just:

```_HeaderType = Any```

**Comment by arjennienhuis** [comment]
```msg['From'] = 2``` actually runs, so maybe:

```_HeaderType = object```

**Comment by gagbo** [comment]
I don't really like using `Any` here, it feels like it's defeating the purpose of typing. I prefer the big union `_HeaderType` as a fix to this problem.

I think `BaseHeader` (and all the other Header types mentionned above) should be part of the union for `_HeaderType`, especially since the [documentation](https://docs.python.org/3.7/library/email.message.html#email.message.EmailMessage.__getitem__) says that `__getitem__` returns a `BaseHeader` instance more often than not.

I don't know how to make overloads so that if `email.headerregistry.HeaderRegistry.use_default_map is True` we can type the [default mappings](https://docs.python.org/3.7/library/email.headerregistry.html#email.headerregistry.HeaderRegistry) correctly.

Also, it would be nice if we were able to deduce the policy from a message, in a way that, for example, `message['date']` would be inferred to be an `Optional[UniqueDateHeader]` for most default policies. But it looks like there's a lot of typing involved for this.

**Comment by gagbo** [comment]
> `msg['From'] = 2` actually runs, so maybe:
> 
> `_HeaderType = object`

This seems to work because the getitem and setitem have different behaviours : while the getitem mostly returns BaseHeader, the setitem seems to dynamically build a class with a parser which takes any object to build a header from. So I think aliasing `_HeaderType` to `object` is not great either

**Comment by arjennienhuis** [comment]
But there is this:

`msg['Date'] = datetime.datetime(2020, 2, 2)`

**Comment by arjennienhuis** [comment]
So `__getitem__` can return a `BaseHeader` but `__setitem__` should accept `object` or `Any`

**Comment by gagbo** [comment]
I'm okay with this too :

- Add `BaseHeader` to the union of `_HeaderType` so `email.message.EmailMessage__getitem__` can return a BaseHeader without difficulties.
- Specify that all specific headers in `email.headerregistry` are derived from `BaseHeader` so they can also work there (`BaseHeader` kind of [specifies](https://docs.python.org/3.7/library/email.headerregistry.html#email.headerregistry.BaseHeader) that the specialized Header have the same interface). This will keep the changes in `_HeaderType` minimal, and allow all kinds of `(Date|Address|...)Header` to be used as `_HeaderType` if need be.
- Let `email.message.EmailMessage.__setitem__` accept anything

**Comment by utkarsh2102** [comment]
> `_HeaderType = Union[str, Header, ContentTransferEncodingHeader, ContentTypeHeader, UniqueDateHeader, SingleAddressHeader, AddressHeader, UniqueAddressHeader, UniqueSingleAddressHeader, MIMEVersionHeader, UniqueUnstructuredHeader, DateHeader, ContentDispositionHeader]`

This workaround makes more sense to me, instead of the above one, no?
At the moment, #2924 implements the same.

**Comment by arjennienhuis** [comment]
Returning a Union is not ok. See https://github.com/python/mypy/issues/1693
