### ISSUE TITLE
profile.Profile and cProfile.profile giving mypy errors

### ISSUE THREAD

**Issue by Yobmod** [python/typeshed#3102]
I get a mypy error when using the timeunit argument for cProfile.Profile and profile.Profile:
"unexpected keyword argument timeunit".
The stub calls it time_unit (with underscore), but the docs say timeunit (no underscore).

Also, while looking this up, should the stubs have "Optional[]" for timer and timeunit, as they have a default of None, and is the first arg custom_timer or timer? . 

cProfile.pyi:
`def __init__(self, custom_timer: Callable[[], float] = ..., timeunit: float = ..., subcalls: bool = ..., builtins: bool = ...) -> None: ....`

cProfile.py:
`Profile(timer=None, timeunit=None, subcalls=True, builtins=True)`

**Comment by srittau** [comment]
It's a bit of a mess. I checked Python 2.7, 3.5, and 3.7.

* `profile.Profile.__init__()` has the following signature in all three versions: `def __init__(self, timer=None, bias=None)`. This seems to be correctly typed, but the [documentation](https://docs.python.org/3/library/profile.html#module-cProfile) is wrong. I'm sure doc patches for CPython are welcome.
* `cProfile.Profile.__init__()`'s argument is indeed called `timeunit`: https://github.com/python/cpython/blob/b607d992e76e485f20be3bfd6b311525123f936b/Modules/_lsprof.c#L713 This is true for all branches, but in Python 2.7 and 3.5 the docstring in `cProfile.py` is wrong. This is fixed in 3.7 and needs to be fixed in typeshed. Patches welcome!
* From my reading, `timeunit` does **not** accept `None` values, but my Python C-API knowledge is limited, so I might be wrong. In case I am right, the comment in `cProfile.py` is wrong.

**Comment by Yobmod** [comment]
I just checked (just by running a script). timer and timeunit both give TypeError if given None.
So they shouldnt be optional (but I dont understand how that works if they have None default args).

I can correct the names in a patch here, then look at the docs patch to match.

**Comment by hauntsaninja** [comment]
I believe all issues discussed are fixed on master.
