### ISSUE TITLE
add dbapi in typeshed?

### ISSUE THREAD

**Issue by ZeeD** [python/typeshed#3216]
is there some plan to add the pep249 dbapi into typeshed? as it is formalized, maybe can be shared across the various db libraries

**Comment by srittau** [comment]
I actually had briefly thought about this myself and we have something similar for WSGI ([PEP 3333](https://www.python.org/dev/peps/pep-3333/)) in `wsgiref/types.pyi`. A practical problem is that since those types do not exist at runtime, in implementations their import needs to be guarded with `if TYPE_CHECKING:`. Overall I'm in favor of this idea, but I'd be interested what other typeshed maintainers think.

**Comment by JelleZijlstra** [comment]
Done in #6643.
