### ISSUE TITLE
typing.TextIO incompatible with io.IOBase

### ISSUE THREAD

**Issue by shannonzhu** [python/typeshed#3225]
I ran into an issue where the type of `sys.stdout` is `_io.TextIOWrapper` at runtime (inheriting from `io.IOBase`), but typeshed specifies this as having type `typing.TextIO`. 

sys.pyi: https://github.com/python/typeshed/blob/master/stdlib/3/sys.pyi#L52

The two never converge, meaning if I write a function expecting `io.IOBase` as an input, I cannot pass it `sys.stdout` without a type error even though `isinstance(sys.stdout, io.IOBase)` is true. 

What's the reasoning for having types defined in `typing` for IOText and IO, as opposed to pointing directly to the actual classes in `io.pyi`? Is there anything blocking this from being fixed?

**Comment by JelleZijlstra** [comment]
I think it's just that things are complicated. There are a lot of "file-like" classes, and the typing IO classes are meant as "protocols" for general files, but they cannot actually be protocols because the file protocol isn't very well defined—there are lots of methods that exist on some but not all filelike classes.

There might be improvements we can make to the typeshed types, but any change risks breaking some existing use case.

**Comment by Hawk777** [comment]
There is another similar issue which might be the same as this, but I’m not sure (if it’s not the same thing, I can make a separate ticket). The following code fails type checking:

```python
fp = open("/tmp/test.txt", "rb", buffering=0)
fp2 = io.BufferedReader(fp)
```

This is because the constructor of `BufferedReader` takes a `RawIOBase`, but the return value of `open` is a `BinaryIO` instead. Obviously this is a bit of a silly thing to do, but it’s neverthless correct and ought to type check.

**Comment by srittau** [comment]
The general consensus is that functions should use narrow protocols for file arguments and concrete classes for return types. Unfortunately, most stubs in typeshed predate protocols, so they require a concrete class as argument, but we are gladly accepting PRs to fix those.

Attributes present special problems, because often they only require a certain narrower type, but accept or default to broader ones. For example, `sys.stdout` basically only requires a `write` and `flush` method, but defaults to `TextIOWrapper`. If we use the latter as type, we prevent monkey patching. If you really need to ensure that `sys.stdout` is a specific type, the best approach is to use a type assert. A better approach is usually to use protocols if possible.
