### ISSUE TITLE
Problem with random.sample(xrange())

### ISSUE THREAD

**Issue by jolaf** [python/typeshed#3374]
The following code:
```python3
from random import sample

sample(xrange(5), 2)
```
produces the following output:
```python3
$ python2 Test.py 
$ mypy -2 Test.py 
Test.py:3: error: Argument 1 to "sample" has incompatible type "xrange"; expected "Union[Sequence[<nothing>], AbstractSet[<nothing>]]"
$ mypy --version
mypy 0.730
$ python3 --version
Python 3.6.8
$ python2 --version
Python 2.7.15+
```
The stub for `random.sample()` is exactly the same for Python 2 and Python 3:
```python3
def sample(population: Union[Sequence[_T], AbstractSet[_T]], k: int) -> List[_T]: ...
```
But for some reason the problem doesn't appear on Python3 (if `xrange` is replaced with `range`).

**Comment by JelleZijlstra** [comment]
Looking at the implementation in Python 2, the argument to `sample()` just needs to support iteration and len(), so maybe we can fix this by defining a custom protocol with `__iter__` and `__len__` and using it as the argument.

In Python 3 the problem doesn't appear because unlike Python 2's xrange(), Python 3's range() is a sequence: https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L1072.
