### ISSUE TITLE
asyncio: Parameterizing _TransProtPair

### ISSUE THREAD

**Issue by brianjyoung** [python/typeshed#3397]
The typeshed for asyncio's transports and protocols continues to irk me; namely, every `loop` coroutine that returns a `(Transport, Protocol)` pair is typed as returning strictly a `(BaseTransport, BaseProtocol)`, which makes actually using any of them a bit of a chore.

Now, I would *like* to go in and specify what type each method returns (e.g. `datagram_endpoint()->DatagramTransport`), but a careful reading shows that the docs are dodgy on guaranteeing anything (`create_connection()`'s return, for example, is 'implementation-dependent'). A nitty-gritty look at the code base shows that asyncio treats its transports more like protocols than anything, frequently returning a completely separate class that just implements all the documented methods of, say, a `DatagramTransport`--I'm not sure there's even a clean way to take care of this. At the very least, I would like to parameterize the protocol that is returned based on the return type of the factory passed in as an argument.

So, my question is: are we as a community opposed to explicitly returning a subclass here, whether due to a strict interpretation of the docs or some other reason? Is there even a good way to go about doing this?

**Comment by srittau** [comment]
Generally, practicality beats purity. For concrete classes we usually can return what the actual implementation returns. For abstract classes, it's a bit more complicated. In cases where it's obvious that a certain kind of transport/protocol is supposed to be returned, and the actual implementation is returning that, we can annotate it like that. If that turns out to be a mistake, we can revert later. Maybe a better alternative is to make liberal use of protocols - even for return values - for asyncio.
