### ISSUE TITLE
Reversible does not subclass Iterable in Typeshed, but does in CPython

### ISSUE THREAD

**Issue by saleemrashid** [python/typeshed#3470]
I am not sure which repository this issue should be filed on:

- In Typeshed, `Reversible` does not subclass `Iterable` so a class that implements both `__iter__` and `__reversed__` should subclass both `Reversible` and `Iterable`

```python
class View(Iterable[_VT], Reversible[_VT]):
    ...
```

- In CPython, `Reversible` subclasses `Iterable`, so the above class would cause the following `TypeError`:

```python
TypeError: Cannot create a consistent method resolution order (MRO) for bases Iterable, Reversible
```

**Comment by saleemrashid** [comment]
Actually, I can obviously work around this issue by moving `Reversible` to the left:

```python
class View(Reversible[_VT], Iterable[_VT]):
    ...
```

But I still don't understand why Typeshed contradicts CPython (and the Python documentation).

**Comment by JelleZijlstra** [comment]
I feel like CPython is wrong here: `Reversible` should mean "something accepted by `reversed()`", and an object that has `__reversed__` but not `__iter__` is accepted by `reversed()`.

In practice this will rarely make a difference though, because it's hard to imagine a realistic reversible object that is not also iterable. And CPython may have compatibility constraints against dropping the `Iterable` base from `collections.abc.Reversible`.

Also note that it's not really necessary for an iterable or reversible class to explicitly have these base classes, since they're protocols: if you just have these methods, your object should be accepted wherever an `Iterable` or `Reversible` is expected.

**Comment by saleemrashid** [comment]
> I feel like CPython is wrong here: `Reversible` should mean "something accepted by `reversed()`", and an object that has `__reversed__` but not `__iter__` is accepted by `reversed()`.

I completely agree, but the Python documentation specifies that `Reversible` is a subclass of `Iterable` so, as you mentioned, I don't think CPython can drop the base class from `Reversible`.

> Also note that it's not really necessary for an iterable or reversible class to explicitly have these base classes, since they're protocols

Unless you're type-checking with MyPy. :wink:

**Comment by srittau** [comment]
Closing in favor of #4615.
