### ISSUE TITLE
any has incorrect type annotation?

### ISSUE THREAD

**Issue by sanderr** [python/typeshed#3498]
The built-in `any` function seems to have an incorrect type annotation. The current signature is
```python
any(i: Iterable[object], /) -> bool
```
I believe it should be
```python
any(i: Iterable[Any], /) -> bool
```
instead.

An example where it goes wrong:
```python
class A(object):
    pass


def filter_func(_: A) -> bool:
    return True


any(filter(filter_func, []))
```
Mypy complains `Argument 1 to "filter" has incompatible type "Callable[[A], bool]"; expected "Callable[[object], Any]`. The signature of filter is
```python
filter(function: Callable[[_T], Any], iterable: Iterable[_T], /) -> Iterator[_T]
```
Now, why does mypy complain? Since `any` expects an `Iterable[object]` as its argument, mypy infers that `_T` should be bound to `object`. So filter expects a `Callable[[object], Any]` as first argument, which doesn't match because `Callable` is contravariant in its arguments.
Therefore it seems that the signature of `any` does not convey the generality it should. It does not play nice with contravariance. Replacing `object` by `Any` does convey this generality.

**Comment by CraftSpider** [comment]
Most likely, it was written like that because [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) advises to use 'object' when a type expects legitimately any possible type, not just an inexpressible one. However, since Mypy treats object as an actual type, this results in contravariants being more -- in fact, incredibly, since as few things are typed as object as possible generally -- strict, not less.

**Comment by sanderr** [comment]
Hmm, you're right, I should've read that first. I still find this a strange choice, but it seems to be according to the mypy conventions. Thanks for your response, I'll close this issue.
