### ISSUE TITLE
Contributing wxpython stubs?

### ISSUE THREAD

**Issue by shalesbridge** [python/typeshed#3637]
While trying to learn the wxpython module, I've been creating type stubs for my own benefit.  It's a big module so the stubs are nowhere near complete, but I was hoping other people might find them handy.

The stubs started as something small that I wrote because I couldn't find existing wxpython stubs, and ballooned in size as more and more wxpython classes got used in my learning project.  Thus most of the stubs don't (yet) follow the style guide in typeshed's CONTRIBUTING.md file.  Before I spent a lot of time reworking them, I thought I'd double check that the stubs would be wanted.  

Apologies if this isn't the place to start the conversation; I thought it was from how I interpreted typeshed's CONTRIBUTING.md file.

**Comment by srittau** [comment]
Sounds great! Having wxpython stubs would be very useful.

**Comment by martinlombana** [comment]
Hi!

I am wondering the same thing, as I am not getting code completion with Pycharm. How do we install the stubs for wxpython?

Thanks,

**Comment by domdfcoding** [comment]
@shalesbridge would you be able to put the stubs you've made so far into a repository (a fork of typeshed itself might be even better)? That way we can see what you've done so far and help you finish them off.

I'd certainly find them very useful.

**Comment by shalesbridge** [comment]
Hey everyone,

Sorry to leave people hanging; things have been pretty nutty here in
meatspace lately.

If people are still interested, I can check in what I've got into a github
repo. It's far, far from complete and I'm pretty sure there's still stuff
that doesn't conform to the typeshed style guidelines, but what is in there
should still be usable typehinting.

**Comment by gre7g** [comment]
Can I push you a PR? Had to add various to check bits I'm using.

**Comment by shalesbridge** [comment]
Since people are interested in wxpython stubs, I've uploaded what I have so
far to github. I wasn't sure exactly what the best way to go about this was
w/r/t typeshed project -I mean, forking/etc. -so I just created a repo at
https://github.com/shalesbridge/wx_typing.git . We can move things into a
typeshed fork or whatever else in the future if that would be more
appropriate.

It's been a while since I've given those stubs some attention and they were
a learning process to start with, so I expect a lot of rough edges will be
found. But at least it's a starting point.

@gre7g I haven't used the push request feature before, but I'd be happy to.

**Comment by AlexWaygood** [comment]
This issue hasn't seen any activity in 2 years, so I'm closing it. Please feel free to open a PR at typeshed at any point if anybody is still interested in contributing stubs for wxpython, however :)

**Comment by Hibou57** [comment]
If anyone is interested, I had some notes on the topic, here: https://github.com/AlexionSoftware/types-wxpython/issues/42

I was trying to fix issues with a similar project but will give-up for now. Feel free to comment if you want.

Side note: useless to install `types-wxpython` for now (may be in the future, I don’t know). For now, it is useful so that MyPy or others don’t complain stubs are missing, but it type-check anything as valid, so nothing (ex. can pass an int instead of a str or what else you want).

**Comment by Hibou57** [comment]
I may be wrong or may be not. People with an interest in this topic, can comment.

There is an aspect of wxPython, which may make it difficult to have all required type annotations.

For type annotation, stubs are not enough. A type annotation requires a name refers to a Python object which exists. Ex if an annotation is `x: C` the class `C` must exist as an object.

In wxWidgets [wx/richtext/richtextbuffer.h](https://docs.wxwidgets.org/latest/richtextbuffer_8h.html) there is this:

    typedef wxVector< wxRichTextLine * > 	wxRichTextLineVector

First, there is no corresponding `wx.richtext.RichTextLineVector` in wxPython [wx.richtext](https://docs.wxpython.org/wx.richtext.1moduleindex.html#module-wx.richtext).

This type, `wxRichTextLineVector`, is, as an example, used in [wxRichTextParagraph Class](https://docs.wxwidgets.org/latest/classwx_rich_text_paragraph.html):

    const wxRichTextLineVector & 	GetLines () const

The corresponding wxPython method, is documented in [wx.richtext.RichTextParagraph.GetLines](https://docs.wxpython.org/wx.richtext.RichTextParagraph.html#wx.richtext.RichTextParagraph.GetLines), and it is said:

    GetLines(self)
        Returns the cached lines.

        Return type:
            Any

In my local copy of the documentation, it just says `PyObject` instead of `Any` and I interpreted it as meaning `Any` anyway.

The type annotation should be:

    GetLines(self) -> RichTextLineVector

But, as far as I know, it cannot be valid if `RichTextLineVector ` does not exists. At least, when loading a module, of a user program, containing such an annotation, there will be an error at load time.

So not just stubs would be needed, but also additional Python modules containing the corresponding missing objects.

To me, this is also a justification to use wsWidgets documentation as source, not wxPython documentation (`Any` is not what's expected in annotations, or rarely … `Any` checks nothing and does not help reliability), but this topic will be for later-later.

Feel free to comment if you like.


As a side note, wxPython is expected to be a Python binding for wxWidgets. But there is `wx.lib` and `wx.adv` at least, which are pure Python modules, not bindings, and also, they are extensions not part of wxWidgets. Since this is pure Python, I believe it should be annotated in source, no in stubs. Or may be type inference would be enough. Having stubs for wxPython as a binding to wxWdigets, is what's expected, I believe. May the pure Python extensions could be treated as if it was something distinct and aside (in my opinion, extensions should have wxWidgets binging as a dependency, not be part of it).
