### ISSUE TITLE
Werkzeug structure has changed as of 1.0.0; some modules don't exist anymore

### ISSUE THREAD

**Issue by jbirch-atlassian** [python/typeshed#3733]
Werkzeug 1.0.0 was tagged and released four days ago. Back in 0.15.0, the release notes included the following item:

> The contrib modules are deprecated and will either be moved into werkzeug core or removed completely in version 1.0.

In 1.0.0, the `werkzeug.contrib` module has disappeared completely — along with a whole lot more in https://github.com/pallets/werkzeug/issues/1477. However, this module and others still exist in Typeshed.

**Comment by srittau** [comment]
PR welcome!

**Comment by jbirch** [comment]
Alright, challenge accepted. I had a quick look at the difference between `stubgen`ing Werkzeug 1.0.0 and what's currently in Typeshed, and differences are relatively significant — significant enough that I started looking at not just updating the now-removed references, but trying to type the entire Werkzeug project.

There's going to be quite a bit of handwaving over some definitions to satisfy "false-negatives are good, false-positives are no bueno". However, I did have one question as I was going through some generated definitions. Where does Typeshed stand on synthesizing types that `stubgen` can't figure out, which aren't documented in the project, but which nevertheless are bounded from an inspection of the implementation?

As a concrete example, Werkzeug defines the [following function](https://github.com/pallets/werkzeug/blob/master/src/werkzeug/wsgi.py#L46-L52), which is naively `stubgen`d as

```python
def get_current_url(environ: Any, root_only: bool = ..., strip_querystring: bool = ..., host_only: bool = ..., trusted_hosts: Optional[Any] = ...): ...
```

Which, following `CONTRIBUTING.md`, is probably more like
```python
def get_current_url(environ, root_only: bool = ..., strip_querystring: bool = ..., host_only: bool = ..., trusted_hosts: Optional = ...): ...
```

However, it seems to me that this can be usefully tightened to
```python
def get_current_url(environ: Mapping[str, str], root_only: bool = ..., strip_querystring: bool = ..., host_only: bool = ..., trusted_hosts: Optional[Sequence[str]] = ...): ...
# or possibly... (I haven't looked deep enough at 2and3 usage of unicode or Text...)
def get_current_url(environ: Mapping[str, str], root_only: bool = ..., strip_querystring: bool = ..., host_only: bool = ..., trusted_hosts: Optional[Sequence[str]] = ...) -> str: ...
```
Does Typeshed fall on the side of eliding types that cannot be deduced statically, or do we allow tightening the types in this way, as long as they don't cause false positives?

**Comment by CraftSpider** [comment]
Not a maintainer, but:
For the first two examples, I'd prefer `param: Any` over bare `param`, as part of what I'm working on is implementing disallow-incomplete-defs, which makes the second one an error.
Also, bare `Optional` is disallows, we run mypy with `disallow-any-generics` which requires the `[Any]` on the end, it may not be implicit.

Overall, we tend to constrain types as strictly as possible without false-positives. If the code looks like it expects a mapping, we tend to type with `Mapping` over `Any` even though strictly some non-mapping types could work.

**Comment by hauntsaninja** [comment]
Also not a maintainer:

`stubgen` is more of a starting point and you should definitely feel free to improve its output! This is much appreciated work. https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#using-stubgen
When in doubt, typeshed follows the implementation over anything else.
https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#what-to-do-when-a-projects-documentation-and-implementation-disagree

On the subject of `Any`, `CONTRIBUTING.md` says:
> Do not use Any to mark unannotated arguments or return values. 

https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#incomplete-stubs

> When adding type hints, avoid using the Any type when possible. Reserve the use of Any for when:
> - the correct type cannot be expressed in the current type system; and
> - to avoid Union returns (see above).
>
> Note that Any is not the correct type to use if you want to indicate that some function can accept literally anything: in those cases use object instead.

https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions

**Comment by srittau** [comment]
Yes, we prefer not to use `Any`, where a type is not annotated yet, so that this can be easily distinguished from cases where `Any` is the best we can do. In the case of `environ`, I'd recommend to use `wsgiref.types.WSGIEnvironment`, even though it's a more restrictive than needs to be. Alternatively, `Mapping[str, Any]` would be the correct type. Thank you for looking into this!

**Comment by jbirch** [comment]
Thanks all for the clarifications and helping me be aware of the other things going on within Typeshed so I don't get in the way of other initiatives.

---
> I'd prefer `param: Any` over bare `param`, as part of what I'm working on is implementing disallow-incomplete-defs, which makes the second one an error.

@CraftSpider, I'm not sure how to reconcile this with `CONTRIBUTING.md`'s "Do not use `Any` to mark unannotated arguments". Are you suggesting that this might change soon with your work? That we might eventually explicitly type such unannotated parameters as `Any`? If this is the case, I'd like to know when the work would land; it would be possible to use this style and target this work for after such a change.

In the mean time, I'll proceed as per `CONTRIBUTING.md` and leave these as bare parameters as I work through, with the intent of swinging back around to reconcile this.

---
Nice catch on `wsgiref.types.WSGIEnvironment` @srittau  — is the driver here because the documentation talks about taking a "WSGI environment", despite the fact that it only requires a `Mapping` functionally?

Possibly more problematically, what _is_  `wsgiref.types.WSGIEnvironment`? It looks like it's only defined in Typeshed, and that Werkzeug isn't strictly tied to it in any way. Is this just a case of a slightly-non-conforming "Type variables and aliases you introduce purely for legibility reasons should be prefixed with an underscore to make it obvious to the reader they are not part of the stubbed API" from `CONTRIBUTING.md`?

---
More generally: I'm slightly confused about `Any`, in that in some cases it seems to be wanted for partially-annotated types. The litmus test I've fallen to at the moment is "Don't use bare `Any`, unless:
* You're filling a type constructor hole (IE, `Optional[Any]`)
* There absolutely is a type restriction, but it can't be expressed for ~rEaSoNs~
* If a function has a `Union` return type"

Please correct me if I'm wrong.

---
All in all, I think this might take me longer than I bargained for; it doesn't seem like I can be as mindless about it over a coffee as I thought at first. I appreciate the ability to take some minor liberties when specifying types for untyped projects.

**Comment by CraftSpider** [comment]
Follow the other's suggestions over mine. They're more right. What I tend to do is spend more time so that instead of `Any` I make the parameters as accurate as possible as I go, and add them where they're missing (plus reviews to catch what I miss).

**Comment by srittau** [comment]
@jbirch Your rules about `Any` sound about right. Please note that these are more guidelines/preference, and I wouldn't reject a PR just because of the use or not of `Any`. 

`wsgiref.types` is a typeshed-only module, not available at runtime. It contains some useful definitions for WSGI modules, and is part of the "typeshed standard library" (if there is such a thing). According to current rules the module should probably be called `wsgiref._types`, though. Whether to use `WSGIEnvironment` or `Mapping[str, Any]` is your decision, since the former is more strict. Please note that an environment that is passed on to other functions outside of werkzeug must be a `Dict` per [PEP 3333](https://www.python.org/dev/peps/pep-3333/).

**Comment by jbirch** [comment]
I've had a lot of questions come up as I've begun working through this, and I was hoping I could get some early feedback from the team.

I've attempted a conversion of the *current* wsgi.pyi, which has not changed in Werkzeug's move to 1.0.0. I figured while I was in here, might as well see what I can contribute to across the board. Unfortunately, the changes are shaping up to be quite expansive. So I guess there's two questions:

1. Would it be best for this issue to simply move around the required types, accepting that while they might still be unspecified or under-specified, they've served us well thus far and improving them is a separate task?
2. If it's worth tackling it, I've got a lot of questions over in https://github.com/jbirch/typeshed/commit/45694c09c397983bd12220dc6062cd8b01d15f5a for just a single file. I'm almost certainly trying to do too much at once, so what's the pragmatic limit of specification for types that's appropriate for Typeshed?

I'm absolutely happy trying to really give Werkzeug a really strong typing, but there's a lot of uncertainty I'm working with that's slowing me down:

- It's super difficult to tell when to use `bytes`/`str`/`Text`/`unicode` here. I see we'll be supporting `2` and `2and3` for a while longer.
- Werkzeug sometimes doesn't seem to conform to PEP 3333...
- I've got a poor understanding of how take advantage of existing types (IE, things that look like they're `Iterator`s, would be nice to not have to re-type those portions...
- I've got a poor understand of how to properly express both variant and invariant generic types, though I'd like to (https://github.com/jbirch/typeshed/commit/45694c09c397983bd12220dc6062cd8b01d15f5a#diff-7ad3c4082780449d2d57377d879a7f0dR7-R8)

Generic feedback on that commit is extremely welcome, but if y'all are slammed I'm happy to change tack and push out the minimal syntax-pushing to put this issue to rest.

**Comment by srittau** [comment]
@jbirch Just a quick answer, not going into detail for now: Maybe it makes sense to just reshuffle the files in a first PR. This keeps the PR smaller and makes it easier to review. Followup PRs can then tackle other issues, possibly one at a time.

**Comment by jbirch** [comment]
Thanks for your feedback Sebastian, it clarified a lot of things in my head.

I've abandoned trying to shore everything up, and have swapped to just moving types around. I expect to have a PR by the end of next weekend.

**Comment by davidism** [comment]
Werkzeug 2.0 will drop Python 2 and include type annotations and `py.typed`. We used monkeytype as a first pass, but that turned out to be extremely unreliable for the complexity of Werkzeug when I reviewed it more closely. I'm currently re-annotating everything by hand. There will definitely be parts that can be improved by a type expert at some point. I didn't think to check typeshed for this sooner, sorry that we've duplicated work.

**Comment by srittau** [comment]
@davidism That's great news! We can then drop werkzeug from typeshed between 6-12 months after it ships with a `py.typed` file. I would recommend looking at the existing stubs, especially those using more complex annotations like overloads or generics. Often these are the result of using annotated code in real life.

**Comment by srittau** [comment]
Closing as the werkzeug stubs will be removed in a few months.
