### ISSUE TITLE
stdlib.3.unitest.mock missing NonCallableMock methods

### ISSUE THREAD

**Issue by rodrigondec** [python/typeshed#3842]
I'm using pycharm and found on this [stack overflow answer](https://stackoverflow.com/a/58053514) that pycharm uses typeshed for its stub autocompletion. 

I'm not having the autocompletions of any Mock or MagickMock methods (such as `assert_called
`, `assert_called_once` and so on).

Browsing the typeshed code I stumbled upon this line
https://github.com/python/typeshed/blob/5162c536c88c4bf46ab74ef09a51165597e90d49/stdlib/3/unittest/mock.pyi#L38

There's a TODO annotation 3 lines above mentioning some false positives
https://github.com/python/typeshed/blob/5162c536c88c4bf46ab74ef09a51165597e90d49/stdlib/3/unittest/mock.pyi#L35

What does the `Any` do on `NonCallableMock`?

Shouldn't we have all methods declared no this `NonCallableMock`? Or this was the cause of the TODO?

I'm volunteering to open a PR if we should have all [mock methods](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock) declared

**Comment by srittau** [comment]
The probable reason `NonCallableMock` (and the other mock classes) were defined like this is so that they can be passed in place as any other object without type checkers complaining. I think I remember some discussion about it where it was suggested that the mock classes should derive from `Any` instead, something like this:

```python
class NonCallableMock(Base, Any):
    def __getattr__(self, name: str) -> Any: ...
    # other methods go here
```

I quickly tried this, and it seems to work fine with mypy. I think this is worth a go.

**Comment by rodrigondec** [comment]
@srittau Assign this to me plz
