### ISSUE TITLE
`assert isinstance(fileobj, typing.TextIO)` fails at runtime

### ISSUE THREAD

**Issue by zackw** [python/typeshed#4108]
Suppose a wrapper function around `open` declared like so:

```
def open_wrapper(fname: str, mode: str, *args: Any, **kwargs: Any) -> IO: ...
```

mypy naturally does not know that `open_wrapper("foo.txt", "wt")` will return a TextIO, so I need to provide a hint when passing that object to a function that accepts a TextIO:

```
from typing import TextIO

def write_data(fp: TextIO) -> None:
    ...

def main():
    with open_wrapper(fname, "wt") as fp:
        assert isinstance(fp, TextIO)
        write_data(fp)
```

This type-checks, but the assertion fails when the program is run, because the actual object returned by `open` in this case is an `_io.TextIOWrapper`, which is _not_ an instance of `typing.TextIO`.  It seems like this should work.

**Comment by srittau** [comment]
This is due to the problematic typing of IO classes in Python, predating protocols. (See numerous other issues here.) `TextIO` can't be checked at runtime, this is not something that can be solved in typeshed.

My personal recommendation is not to use the IO classes, but use custom protocols for argument types. We also gladly accept PRs in typeshed that change IO arguments to protocols. If that doesn't work, you need to to `cast()` or `# type: ignore`.
