### ISSUE TITLE
Third-party pyVmomi stubs are incomplete which lead to many mypy violations

### ISSUE THREAD

**Issue by dgilland** [python/typeshed#4182]
With mypy 0.780, typeshed now includes third-party pyVmomi stubs. However, the pyVmomi library has a very dynamic data model with a lot of objects and attributes that can vary across vSphere/vCenter versions. This makes providing stubs for it very difficult.

The new third-party pyVmomi stubs in typeshed are incomplete, and mypy is now reporting a lot of false-positive "has no attribute" violations for our code bases that use pyVmomi data models extensively.

Is there a way to disable certain typeshed third-party stubs? Or is it possible for the pyVmomi stubs to be defined in a way that doesn't result in a large number of false-positives? I'd prefer not to have to add `# type: ignore` throughout our code bases for every single attribute access on pyVmomi models that aren't defined in typeshed.

**Comment by JelleZijlstra** [comment]
The stubs were added in #3921.

If possible, we should add `__getattr__` method to the appropriate classes and modules so that we don't trigger false positives. Otherwise, the best option may be to remove the stubs for now.

In the future we'll move away from typeshed's current "all or nothing" model, so that it's possible to selectively uninstall stubs that aren't helpful for users.

**Comment by Akuli** [comment]
you can remove (or rename) `site-packages/mypy/typeshed/third_party/2and3/pyVmomi`

**Comment by srittau** [comment]
A PR that adds many `__getattr__()`s has been merged, which hopefully improves the situation. Please send PRs if there are still problems.
