### ISSUE TITLE
Change isort config and turn on isort in CI

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#4288]
While trying to land isort in CI in #3329, I discovered that the behavior of our current isort config depends on whether some modules (e.g., `typing_extensions`) are installed in the runtime environment where isort is run. This is bad because it means that contributors running isort locally may get different behavior depending on what libraries they happen to have installed in their local environment.

I'm guessing that this has to do with isort's behavior of sorting imports into "sections" of standard library, third-party, and first-party imports. Looking at https://github.com/timothycrosley/isort/wiki/isort-Settings, maybe we need to set `default_section`? Perhaps we should also mark typing-extensions and _typeshed as "standard library" because in the context of typeshed, they essentially are part of the standard library.

**Comment by hauntsaninja** [comment]
I think just setting `default_section` won't work, since presumably if isort detects an installation of `typing_extensions` it'll no longer use the default section. 
We should also be careful about `third_party` stubs, since we can't exhaustively override the sections of possible imports.
The two options I can see are:

- Set `virtual_env` to some random folder. This should hopefully guarantee that isort isn't dependent on contributors' environments.
- Set `default_section` to `THIRDPARTY`, so that whether or not isort detects a library the resulting section is hopefully the same. This might have slightly worse ordering though?

I'm in favour of explicitly marking those as "standard library".
