### ISSUE TITLE
Missing Intellisense Autocompletions for urllib

### ISSUE THREAD

**Issue by sharoncxu** [python/typeshed#4511]
Currently using Intellisense + Pylance Extension in VS Code. 

In the following code, the autocompletion doesn’t show getcode() as an option when writing “f.” in the last line. (The completion works fine for “urlib.” and “urllib.request.”)

`import urllib.request
import urllib.parse

f = urllib.request.urlopen("https://www.microsoft.com")

f.getcode()`

**Comment by hauntsaninja** [comment]
getcode exists in typeshed. The issue is that the return type of urlopen is currently typed as Any.

There's more context here, for when that return type was changed:
https://github.com/python/typeshed/issues/3026
https://github.com/python/typeshed/pull/3045

I'm going to close, since those changes were intentional about what they were doing.
