### ISSUE TITLE
Drop the consistency checks?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#4674]
One common source of CI failures are the consistency checks. They also often force us to add version checks, complicating stubs. Builtins are a particularly egregious example. On the other hand, keeping the Python 2 stubs up-to-date is low priority by now. For those reasons I suggest to drop the consistency checks, clean up the affected stubs, and let them diverge. We could also split `stdlib/2and3/builtins.pyi` into Python 2 and 3 versions.

**Comment by JukkaL** [comment]
I agree that keeping Python 2 stubs up-to-date is not important, especially if this adds friction to improving Python 3 stubs. I also like the idea of splitting `builtins.pyi` into Python 2 and 3 versions. 

I suspect that we will have a non-trivial number of Python 2 users for several years at least, so having Python 2 stubs continues to be important. However, keeping them mostly in maintenance-only mode seems fine, since Python 2 will hopefully go away at some point, and most new code is written in Python 3.

What about splitting other 2-and-3 stubs into separate Python 2 and 3 versions, and focusing improvements on the Python 3 versions in the future? This could be helpful at least for stubs that see frequent changes.

**Comment by srittau** [comment]
> What about splitting other 2-and-3 stubs into separate Python 2 and 3 versions, and focusing improvements on the Python 3 versions in the future? This could be helpful at least for stubs that see frequent changes.

I was considering this as well, but didn't want to bring it up at this point. But +1 from me.
