### ISSUE TITLE
Typeshed typing.pyi in stdlib mismatches typing.py

### ISSUE THREAD

**Issue by ZoranPavlovic** [python/typeshed#4694]
**Examples**:

-  The function "_Alias" in the typeshed pyi is with an uppercase A whereas in the python file it is "_alias".
- _GenericAlias is missing from the pyi file in typeshed

**Source files**:

- Python 3.7 typing.py file [here](https://github.com/python/cpython/blob/3.7/Lib/typing.py).
- Typeshed typing.pyi file [here](https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi).

Is there a specific reason for this that I am misunderstanding, or is it simply a misalignment that can be resolved with a PR to the Typeshed pyi file?

**Comment by JelleZijlstra** [comment]
The examples you mention are private implementation details. Because the `typing` module is at the heart of the typing system (obviously), it contains a fair amount of implementation details, and those implementation details are likely to be different in the runtime and stub files.

We can fix particular discrepancies like the ones you mentioned if they're leading to concrete problems, but in general we should be careful with changes to `typing.pyi` since type checkers may rely on the current declarations.

**Comment by hauntsaninja** [comment]
Yeah, in addition to what Jelle mentioned, I'll also say that these are also implementation details that have changed a lot (typeshed currently supports Python 3 versions back to 3.5) and modelling all of that gets pretty complex for little benefit and lots of potential harm to type checkers. The other thing I'll mention that in addition to typeshed.pyi's details mattering a lot to type checkers themselves, some of these details are even surfaced to users through type checker error messages.

I'd accept PRs that add missing definitions in typing.pyi so that things like autocomplete work for when people want to (ab)use those details, but I would hesitate for PRs that try to mirror all the implementation for typing.py too closely.
