### ISSUE TITLE
Can't write a wrapper function around sorted.

### ISSUE THREAD

**Issue by MSK61** [python/typeshed#4738]
I had a wrapper function around sorted that looks like this:
```
import typing
_T = typing.TypeVar("_T")

def sorted_tuple(elems: typing.Iterable[_T],
                 key: typing.Callable[[_T], object] = None) -> typing.Tuple[_T, ...]:
    return tuple(sorted(elems, key=key))
```

After a recent update of mypy(to 0.790) mypy is raising errors about my wrapper function:

    error: Value of type variable "_LT" of "sorted" cannot be "_T"
    error: Argument "key" to "sorted" has incompatible type "Optional[Callable[[_T], object]]"; expected "None"
I see here https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi that sorted is defined with two overloads, but my function is acting as a wrapper for the two overloads. Trying to use overloaded definitions for my wrapper function would fail as I'm using type hints inside a source file(.py) and the last definition of the wrapper can't go without type hints, which it would still be a problem to come up with. The only way, though not so elegant, is to use Any in place of all types.
```
import typing
from typing import Any

def sorted_tuple(elems: typing.Iterable[Any],
                 key: typing.Callable[[Any], Any] = None) -> typing.Tuple[Any, ...]:
    return tuple(sorted(elems, key=key))
```
Is there any better approach?

**Comment by JelleZijlstra** [comment]
The problem is that your function accepts any type (because there's no bound on `_T`), but sorted() only accepts comparable types. We recently changed the stubs to reflect that.

You should probably have overloads similar to the ones you found in `builtins.pyi`. You may have to fall back to Any for the implementation, but that shouldn't be a big problem because the overloads will be used to type check callers of the function.

Feel free to ask further questions on https://gitter.im/python/typing.
