### ISSUE TITLE
defaults argument for configparser.ConfigParser when allow_no_value=True

### ISSUE THREAD

**Issue by mike0sv** [python/typeshed#4773]
I want to be able to provide `None` as the default value like this `ConfigParser(defaults={'option': None})`, but the type of `defaults` is `Optional[Mapping[str, str]`, not `Optional[Mapping[str, Optional[str]]`

**Comment by srittau** [comment]
Generally in typeshed we try to follow implementation rather than documentation. In this case I am a bit wary that providing `None` values as defaults has unintended side effects. For example, we would need to change the return type of `defaults()` as well. Maybe @ambv (who is listed as [configparser expert](https://devguide.python.org/experts/)) has an opinion?

**Comment by mike0sv** [comment]
My point is that [here](https://github.com/python/cpython/blob/975022b77b0024ea1548f19d5f91aba5ba1eed59/Lib/configparser.py#L1183) `None` is treated as valid if `allow_no_value` is set to `True` (sorry, forgot to mention that earlier). This validation is called for every default value in provided `defaults`. And this actually works, except mypy reports this as an error

**Comment by srittau** [comment]
Ah, I missed that. In that case it would make sense to use an overload: Allow `None` values iff `allow_no_value==True`. PR welcome!
