### ISSUE TITLE
Fix autogenerated protobuf stub's nonexistent import

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#4815]
My PR (#4814) is failing tests in a part I didn't touch:
```
running mypy --python-version 3.9 --strict-optional --no-site-packages --show-traceback --no-implicit-optional --disallow-any-generics --disallow-subclassing-any --platform linux # with 1042 files
third_party/2and3/google/protobuf/util/json_format_proto3_pb2.pyi:45: error: Cannot find implementation or library stub for module named 'google.protobuf.unittest_pb2'
third_party/2and3/google/protobuf/util/json_format_proto3_pb2.pyi:45: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1042 source files)
```
(and repeated for other versions). The same seems to be happening for other recent PRs, e.g. #4813 and #4811.

**Comment by hauntsaninja** [comment]
Did some investigating, it looks like the trigger for this was syncing typeshed: https://github.com/python/mypy/pull/9794
The error looks legitimate, the file was removed in https://github.com/python/typeshed/pull/4785/files#diff-328c07f017a31da756c9b78484dbeab4ec7757a29092a2ba2c9afe2d4bc63a50 but continues to be imported. I assume mypy managed to continue to find the file in its bundled typeshed, which is a little weird (maybe mypy_test should pass in `--custom-typeshed-dir`).

I'm not sure how to fix, since the file is autogenerated, so cc @nipunn1313

**Comment by hauntsaninja** [comment]
(In case Nipunn doesn't see this soon, just removing `third_party/2and3/google/protobuf/util/json_format_proto3_pb2.pyi` entirely seems to be enough to get things green)

**Comment by srittau** [comment]
I have replaced the missing import with `Any` for now. This should work, but of course still needs a proper fix.

**Comment by nipunn1313** [comment]
Fixed! My mistake.
Thanks for the report @gvanrossum - and thanks for the quick fix @srittau - bought me time to look into a proper fix.
