### ISSUE TITLE
How do I type a "file object"?

### ISSUE THREAD

**Issue by Michael0x2a** [python/typeshed#482]
I'm currently trying to add types for the [selectors](https://docs.python.org/3/library/selectors.html) module, and am running into some difficulty figuring out the correct way to type a "file object".

The documentation for [BaseSelector](https://docs.python.org/3/library/selectors.html#selectors.BaseSelector) states that...

> fileobj is the file object to monitor. It may either be an integer file descriptor or an object with a fileno() method.

However, the problem is that there doesn't seem to an ABC that exactly describes "an object with a fileno() method". I initially tried using [io.IOBase](https://docs.python.org/3/library/io.html#io.IOBase) and `typing.IO`, but the socket class doesn't seem to extend either base class (or share many of the methods, for that matter).

What is the correct course of action here? Should I try and petition to add a new ABC/modify the io module to try and unify all these different kinds of "file-like objects", or should I just settle for something more ad-hoc like the following?

```python
from socket import socket
from io import IOBase
from typing import AnyStr, IO, Union

FileObj = Union[int, socket, IOBase, IO[AnyStr]]
```

(Oddly, io.IOBase and typing.IO also seem to be two distinct classes despite them being fairly similar -- I'm not sure if that was intentional or not)

**Comment by gvanrossum** [comment]
This is one more use case for [structural typing](https://github.com/python/typing/issues/11), but in the meantime I would do something ad-hoc like you describe rather than make yet another custom ABC (those are hard to introduce and hard to get rid of).

I actually expect that the only real use cases are sockets and ints -- by the time someone has an IOBase or IO[...] instance they are probably talking about a disk file, which selectors don't support. Also most subclasses of IOBase do some form of buffering which makes using a selector a no-no. Calling fileno() isn't really a hardship, and callers that don't have any other reference to the object wouldn't know what to do when they got called back.

Regarding IOBase vs. IO[...], that area is a bit of a mess, but basically the concrete implementation classes don't really have a proper subtyping relationship, so for the type system we are probably wise to ignore them.

**Comment by Michael0x2a** [comment]
Thanks for the clarifications!

**Comment by Eric-Arellano** [comment]
Could this be revisited now that [protocols](https://mypy.readthedocs.io/en/latest/protocols.html) are supported in MyPy and Python 3.8? Make the type be `Union[int, SupportsFileNo]`, where `SupportsFileNo` is a custom protocol that checks for the function `fileno()`.

I'd be happy to submit a patch if you all would like.

**Comment by srittau** [comment]
Please go ahead. This sounds like the right solution.
