### ISSUE TITLE
Dict with kwargs

### ISSUE THREAD

**Issue by timrid** [python/typeshed#4846]
I would like to be able to write the following, recognizing the correct types:

```python
a = dict(helloworld=1)
reveal_type(a)
```

In **mypy** this is correctly identified as: `note: Revealed type is 'builtins.dict[builtins.str*, builtins.int*]'`.

But with **pyright** / **pylance** the key type it is `Unknown`.
![image](https://user-images.githubusercontent.com/6593626/102818144-5ea48c00-43d1-11eb-9645-6c60852b436e.png)

I also asked this in https://github.com/microsoft/pyright/issues/1300, where @erictraut pointed me here. It is apparently not a problem of pyright, but of the typshed stubs. So my question is if it is possible to change the current implementation:

```python
class dict(MutableMapping[_KT, _VT], Generic[_KT, _VT]):
    # NOTE: Keyword arguments are special. If they are used, _KT must include
    #       str, but we have no way of enforcing it here.
    @overload
    def __init__(self, **kwargs: _VT) -> None: ...
    @overload
    def __init__(self, map: SupportsKeysAndGetItem[_KT, _VT], **kwargs: _VT) -> None: ...
    @overload
    def __init__(self, iterable: Iterable[Tuple[_KT, _VT]], **kwargs: _VT) -> None: ...
    def __new__(cls: Type[_T1], *args: Any, **kwargs: Any) -> _T1: ...
    ...
```

against this:

```python
class dict2(MutableMapping[_KT, _VT], Generic[_KT, _VT]):
    @overload
    def __new__(cls, **kwargs: _VT) -> "dict2[str, _VT]": ...
    @overload
    def __new__(cls, map: SupportsKeysAndGetItem[_KT, _VT], **kwargs: _VT) -> "dict2[_KT, _VT]": ...
    @overload
    def __new__(cls, iterable: Iterable[Tuple[_KT, _VT]], **kwargs: _VT) -> "dict2[_KT, _VT]": ...
    ...
```

The main difference is, that the `__new__` with `kwargs` has a return type with `Dict[str, _VT]`.

In my tests it seems to work with pyright in the way i expect. Are there any disadvantages?

**Comment by srittau** [comment]
This could indeed be improved. I tried a slightly different approach in #4848, although this is a high-risk change, so it will need some testing.

**Comment by timrid** [comment]
Your solution looks even better than mine.
Unfortunately your change does not solve the problem in pyright for me. But this may be a problem of pyright @erictraut ?

**Comment by erictraut** [comment]
This solution makes use of an annotated `self` parameter within an overloaded `__init__` method, and it is assumed that this annotation will influence the resulting type of a constructed object. This technique was informally agreed upon in a mypy discussion and is undocumented in any PEPs. It appears to be used in only two cases so far in typeshed stubs: the `array` class defined in `array.pyi`. I recently learned about this technique because of a bug that someone reported.

This approach is problematic for pyright because of the way it implements constructor type evaluation. The `__init__` method is bound to the object before the object's type is fully known and before the TypeVar constraint solver is run. In response to the bug report, I implemented a limited (and somewhat hacky) solution that works with the existing uses of this technique in typeshed stubs. This solution @srittau introduced here for `dict` employs a more complex annotation that includes a TypeVar (`VT`) for one of the type arguments, and my implementation falls apart because of this. If you move ahead with this solution, I'll need to rethink my entire approach for constructor type evaluation which will likely involve a big change.

If typeshed stubs are going to start to rely on this `self` parameter approach more, I'd like to see it formally documented in a PEP. It feels like an inconsistent hack to me, but if the specific rules for constructor type evaluation were spelled out more clearly in a standard, I'd probably feel more comfortable with it.

**Comment by erictraut** [comment]
I found a way to support the proposed change to the `dict.__init__` method without a major rewrite of the constructor logic in pyright.

**Comment by timrid** [comment]
That sounds great.
Is this then a general solution for the `self` parameter approach for `__init__` methods, or another hacky way only for the `dict.__init__` method?

**Comment by erictraut** [comment]
It's more general than my original solution, but it's still somewhat limited. In particular, the class in the annotation must match the class that is declaring the `__init__` method, and it's allowed to use type variables as first-level type arguments. The solution would fall apart if you attempted to use deeper-nested type variables such as `self: Dict[str, List[_VT]]`. I don't think that will ever come up, but without a spec, it's hard to say. That's why I still think there should be a PEP created for this if it is going to be used in typeshed stubs.

**Comment by JelleZijlstra** [comment]
Can we avoid the hack by overloading `__new__` instead of `__init__`? That's probably more correct for dict anyway.

**Comment by srittau** [comment]
Using `__new__` is problematic, because the `cls` type needs to be generic, which wouldn't work:

```python
class dict(Generic[_KT, _VT]):
    @overload
    def __new__(cls: Type[_T[Any, Any]], ...) -> _T[Any, Any]: ...
    @overload
    def __new__(cls: Type[_T[str, _VT]], **kwargs: _VT) -> _T[str, _VT]: ...
    etc.
```
