### ISSUE TITLE
tkinter bbox in Misc

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4890]
This is in Misc:

```
# commented out to avoid conflicting with other bbox methods
# bbox = grid_bbox
```

I do not see any problem in  this change:

`
bbox = grid_bbox
`

Perhaps i do not see something?

**Comment by Akuli** [comment]
Widgets have a `bbox()` method that does a different thing than `grid_bbox()`. This creates mypy errors.

The `bbox = grid_bbox` line in tkinter was probably intended to allow `tkinter.Grid.bbox(widget)` as an alternative to `widget.grid_bbox()`. Nowadays everyone seems to just use widget methods instead of accessing the `Grid` class directly.

**Comment by melassa** [comment]
Because every widget has a bbox method (which Mypy does not know), if we do not put it in Misc (and let that some widgets override it) we should add it to all widget missing a bbox  method stub.

**Comment by Akuli** [comment]
You can try to uncomment `bbox = grid_bbox` and add `# type: ignore` to all lines that cause a mypy error.

**Comment by melassa** [comment]
Test failed. Mypy does not like it. Better add bbox to Widgets.

**Comment by Akuli** [comment]
This can be closed now
