### ISSUE TITLE
tkinter text configure option accepts also int, float

### ISSUE THREAD

**Issue by melassa** [python/typeshed#5076]
`text` configure option accepts `int`, `float` not only `str`
```
tk.Label(text=3)
tk.Label(text=3.5)
ttk.Label(text=3)
ttk.Label(text=3.5)
tk.Button(text=3)
tk.Button(text=3.5)
ttk.Button(text=3)
ttk.Button(text=3.5)
```

To say the truth, it accepts any value and auto convert it to string.

**Comment by Akuli** [comment]
When I wrote the stubs, I made `text` arguments have type `str`. My intention was that `text=some_int` is likely a programming error, although I can see how it's useful.

I still don't think we should accept anything as `str`. For example, I want mypy to detect if I accidentally write `text=self.method` instead of `text=self.method()`. Ideally there would be a way to say "accept anything that has a meaningful string representation", but currently that's not possible.

**Comment by melassa** [comment]
I understand.
With a Protocol could be done "accept anything that has a string representation" but it is almost like `Any`.

**Comment by JelleZijlstra** [comment]
Yes, any Python object supports `str()`, and while `str(some.method)` is probably not what you want your UI to show, there's no way to tell that to the type system.

Perhaps just adding `int` and `float` to allowed types here would be helpful without causing significant false negatives?
