### ISSUE TITLE
What is the justification for the contradictory code in PEP 484

### ISSUE THREAD

**Issue by markshannon** [python/typeshed#519]
The current version of PEP 484 states:
> In non-stub code, there is a similar special case:
```
from typing import IO
stream = None  # type: IO[str]
```
> Type checkers should not complain about this (despite the value None not matching the given type), nor should they change the inferred type to Optional[...] (despite the rule that does this for annotated arguments with a default value of None ). The assumption here is that other code will ensure that the variable is given a value of the proper type, and all uses can assume that the variable has the given type. 

Why shouldn't they complain about this obviously contradictory statement?

BTW, I don't remember this being in the draft PEP that I accepted, but git blame says it was added 2 days before my post accepting the PEP. Not sure what happened there.

**Comment by gvanrossum** [comment]
(You probably meant the python/typing tracker, but oh well.)

Funny you should ask, because in PEP 526 this would be spelled
```
    stream: IO[str]
```
without an initial value.

In stubs we currently spell it like this:
```
    stream = ...  # type: IO[str]
```
but that's not great when running the code because this assigns the object Ellipsis which is just going to be even more confusing (few people know there's even an object with that name), plus it doesn't work in Python 2 (where `...` is only allowed in slices).

The use case is exactly the use case for that syntax in PEP 526: indicating the type of the variable (typically an instance variable) to the type checker without giving it a value -- there is no other mechanism in PEP 484 to do that, unless you count adding an annotation to the first assignment to this instance variable in `__init__`, which is pretty hard to read if there are multiple assignments guarded by an `if`/`elif`/`else` chain.

E.g. we found something like this at Dropbox:
```
def __init__(self, field_type: type) -> None:
        self.field_type = None  # type: List[type]
        if field_type in integer_types:
            self.field_type = integer_types
        elif field_type is float:
            self.field_type = float_types
        else:
            self.field_type = [field_type]
```
Without the PEP 484 feature under discussion we'd have to put the type annotation on the first assignment to self.field_types, where it is kind of hidden. (You can argue whether it's better in the class or in `__init__`; PEP 484 and mypy allow either.)

**Comment by gvanrossum** [comment]
Closing as there is no action for typeshed. @markshannon if you disagree with my explanation please open a new issue in https://github.com/python/typing/issues.
