### ISSUE TITLE
python 3.9.2 windows argparse no module _typeshed

### ISSUE THREAD

**Issue by Stargateur** [python/typeshed#5201]
MCVE:
```python
import argparse
```

Error:
```none
Traceback (most recent call last):
  File "C:\Users\Star\git\optomata\options.py", line 1, in <module>
    from _typeshed import AnyPath
ModuleNotFoundError: No module named '_typeshed'
```

At this point I don't know what to do.

https://github.com/python/typeshed/issues/5021 doesn't seem related

**Comment by Stargateur** [comment]
OK nevermind, visual studio code troll me

**Comment by RobertoTables** [comment]
> OK nevermind, visual studio code troll me

So, what was the solution?

**Comment by Stargateur** [comment]
none, I copy paste a code and somehow scroll and never saw the problem was on the first line.

**Comment by manudut** [comment]
Yeah, happened exactly the same to me...

**Comment by Navneety007** [comment]
Yeah same here people

**Comment by Akuli** [comment]
Can we get more details about how this is happening? What editor and version? What is the name of the file you save the code into? Which button do you click in the editor to run it?

**Comment by BradMclain** [comment]
I had the same error and thought i was going mad for a second.

For those asking for more details visual studio code autocomplete had added the following at top of file and then scrolled down causing line 1 to be hidden. As @Stargateur indicates this even happens in very short files.
```
from _typeshed import OpenTextMode
```

**Comment by TheRealDalunacrobate** [comment]
> 
> 
> I had the same error and thought i was going mad for a second.
> 
> For those asking for more details visual studio code autocomplete had added the following at top of file and then scrolled down causing line 1 to be hidden. As @Stargateur indicates this even happens in very short files.
> 
> ```
> from _typeshed import OpenTextMode

```
    from _typeshed import OpenTextMode
ModuleNotFoundError: No module named '_typeshed'
```

I'm blocked there ...

**Comment by gabriribeiro5** [comment]
Why this happened?
[answer]:

Hey, guys!  This happens because inside the code there's some attribute being called when creating basic functions like

 `open(file="AnyPath", mode=OpenTextMode)`
 
Notice that 'AnyPath' and 'OpenTextMode' aren't variables you created in your code, they are already built in to python and your code is importing them and, whenever we call something from outside our file.py, we must declare it by using

`from module import object`

What VSCode did was complete the code with those necessary commands for this attributes to work

And what those attributes do?
I haven't gone that far in my research but I suppose it compiles some "raw" parameter for the function open()

`open(file/path/and/name, openingMode): #the openingMode defines the purpose of opening the file`
`open(myFile, "r") #means the file is open for read only privillege` 
`open(myFile, "w") #means the file is open for write only privilleges`
`open(myFile, OpenTextMode) #probably means it's open with all privilleges`

**Comment by agungkrishna-code** [comment]
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from _typeshed import ...

Use this work for me

**Comment by Mwatchorn26** [comment]
Same here, it automatically added the "from _typeshed import" statement at line 1.
I wonder - Is this a VS Code issue, or caused by an extension?
