### ISSUE TITLE
mypy_primer comment timeout

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5367]
Sometimes mypy_primer comment CI job times out. It seems to happen only when adding multiple commits to the pull request before mypy_primer finishes. See #5365 for an example.

**Comment by JelleZijlstra** [comment]
I noticed on some PRs that I had to click the button to approve runs many times for a single PR. Not sure how that logic works.

**Comment by srittau** [comment]
I think you have to approve the run for each push in the first PR of a contributor. I guess that's a bug, but who knows.

**Comment by Akuli** [comment]
A possible fix would be to add `needs: mypy_primer` to the comment job. But then it would need to be in the same file with running mypy_primer, so mypy_primer running would get an unnecessary `pull-requests: write` permission. @hauntsaninja Is that why this wasn't done that way in the first place?

**Comment by JelleZijlstra** [comment]
I believe that would cause a security issue because user code would be able to influence a job with the write permission.

**Comment by hauntsaninja** [comment]
Yeah, that's why they're separate workflows. Without the newly added permissions field, I think the write permission wasn't even scoped. Maybe it's now possible to set more granular permissions so that only the commenting part can write? https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idpermissions

**Comment by hauntsaninja** [comment]
#5428 resolves
