### ISSUE TITLE
pypi.org missing sdists for types-* packages

### ISSUE THREAD

**Issue by benbariteau** [python/typeshed#5643]
I tend to download sdists and rebuild wheels to make sure they work against my system dependencies. This means that if I use pip with `--no-binary :all:` (to guarantee this happens) I can't download the any types packages. I get that source wheels and sdists are semantically the same most of the time, but having an sdist is really useful and they should be uploaded.

**Comment by JelleZijlstra** [comment]
Agree that we should do this. This will have to happen in the stub-uploader directory, probably somewhere around https://github.com/typeshed-internal/stub_uploader/blob/main/scripts/build_wheel.py.

**Comment by nemacysts** [comment]
@JelleZijlstra I've opened a PR (https://github.com/typeshed-internal/stub_uploader/pull/19) that I *think* should resolve this, but I can't seem to add any reviewers :)

**Comment by xhochy** [comment]
On conda-forge, we also prefer to build all Python packages from source distributions instead of wheels. Especially the automation we have for simple Python packages as these ones here are built around source distributions. Thus we would very much also wait for the upload of `sdist` to PyPI before packaging them there. For us, this makes a difference between "running a script for 1h with probably 2-3 min human effort" vs "hours of human effort to extend the automation".

@nemacysts Thank you for already putting in a PR :)

**Comment by srittau** [comment]
And it seems to work: https://pypi.org/project/types-bleach/#files
