### ISSUE TITLE
stubtest unused allowlist for third party stubs

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5654]
How does this work currently? In #5652, I found that in a third-party stub, I needed to delete unused entries to make stubtest pass. But there's still `.github/workflows/stubtest-unused-allowlist.yml`, which is for stdlib only. So it's fine to leave unused stdlib entries in a PR, but not for third-party libraries.

Why the inconsistency? Can we unify this somehow so that it actually makes sense?

**Comment by srittau** [comment]
Yeah, I would prefer to accept unused allow lists in third-party stubs as well to keep friction as low as possible and then integrate it into the (weekly?) cron job.

**Comment by hauntsaninja** [comment]
I just didn't add a Github action for automatically cleaning up third party stubtest allowlists. Once we have that, should be fine to use `--ignore-unused-allowlist` in `stubtest_third_party.py`.
The logic for cleaning up third party allowlists should be pretty simple, since we only have one allowlist (as opposed to the common + python version + platform combination + etc that we have for stdlib).

**Comment by Akuli** [comment]
We ended up going in a different direction in #6406.
