### ISSUE TITLE
Latest mypy fails to find `enum34` with `--py2`

### ISSUE THREAD

**Issue by godlygeek** [python/typeshed#5683]
**Bug Report**

I'm not sure if this belongs in `mypy` or `typeshed` (or both), but: the latest version of `mypy` believes that the latest version of the `enum34` stubs are not Python 2 compatible, despite being in a `-python2-stubs` package.

**To Reproduce**

1. `python3.9 -m venv /tmp/39`
2. `. /tmp/39/bin/activate`
3. `pip install 'mypy[python2]' 'types-enum34'`
4. `mypy --py2 -c 'import enum'`

**Expected Behavior**

mypy should have found the `enum` stubs:

```
(39) $ cat /tmp/39/lib/python3.9/site-packages/enum-python2-stubs/METADATA.toml
version = "0.1"
```

**Actual Behavior**

```
<string>:1: error: Library stubs not installed for "enum" (or incompatible with Python 2.7)
<string>:1: note: Hint: "python3 -m pip install types-enum34"
<string>:1: note: (or run "mypy --install-types" to install all missing stub packages)
<string>:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

I think that `_is_compatible_stub_package` is deciding that `enum-python2-stubs` isn't Python 2 compatible, which seems... odd. But the only metadata for it is `version = "0.1"` - it doesn't have a `python2 = true`.

This is either a bug in `typeshed` (that the Python 2 `enum34` stubs don't declare that they're for Python 2) or a bug in `mypy` (that `-python2-stubs` packages should be assumed to support Python 2 but aren't).

**Your Environment**

- Mypy version used: 0.910
- `types-enum34` version: 0.1.7
- Mypy command-line flags: `--py2`

**Comment by hauntsaninja** [comment]
Thanks for the report! I think this is a typeshed issue since it's missing the field in METADATA.toml and https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-stubs implies it should be there, but I know typeshed has made some changes (https://github.com/python/typeshed/pull/5660/files) so it's possible I'm wrong or outdated. At the very least, seems like typeshed could have communicated a breaking change better.

**Comment by srittau** [comment]
The `python2 = true` field is should only be added if the top-level stubs are for Python 2 and 3, so the field missing is correct. I'll look into this.

**Comment by srittau** [comment]
mypy indeed assumes that the `METADATA.toml` file contains a `python2 = true` key for Python 2 packages. This assumption isn't true anymore since #5660. The most pragmatic workaround is to re-add the key to Python 2 packages for now and fix mypy for the next release.

**Comment by srittau** [comment]
This problem should be fixed with the next version of all Python 2 packages. We still need to fix mypy, though.

**Comment by JukkaL** [comment]
Even if we fix this in mypy, any users still on mypy 0.90x or 0.910 won't be able to use the latest stubs if we revert the metadata change, right? We should probably give users time to migrate after a fix becomes available. If we'd make a mypy 0.911 bugfix release with the update, we could revert the change sooner. Since mypy 0.920 won't support Python 3.5 any more, Python 3.5 users will be stuck on 0.91x until they move to a more recent Python version. Not sure if many projects still support Python 3.5, though.

**Comment by srittau** [comment]
I'd say removing `python2` field has no priority, but we should fix it in the next mypy and then remove it again at some point in the future. Are there realistically people stuck on checking Python 2 code with Python 3.5 that a bugfix release is important?

**Comment by srittau** [comment]
Also there is an easy workaround for people stuck on 0.910: Don't upgrade the stubs either!

**Comment by srittau** [comment]
This issue seems mostly resolved. As typeshed will most likely drop Python 2 support in the foreseeable future, remove the python2 keys now seems unnecessary.
