### ISSUE TITLE
logging.Logger.addFilter

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5700]
```
porcupine/plugins/langserver.py:789: error: Argument 1 to "addFilter" of "Filterer" has incompatible type "HackFilter"; expected "Union[Filter, Callable[[LogRecord], int]]"
```

`HackFilter` is a class that has a `filter()` method but doesn't inherit from anything. This should work, according to docs: "You don’t actually need to subclass Filter: you can pass any instance which has a filter method with the same semantics." https://docs.python.org/3/library/logging.html

`Callable[[LogRecord], int]` seems wrong. The imlpementation basically does `self.filters.append(filter)`. Does it really handle callables and objects with a `.filter()` method everywhere where it uses `self.filters`?

**Comment by JelleZijlstra** [comment]
Yes, sounds like we should be using a Protocol with a filter method.

**Comment by Akuli** [comment]
Actually, `Callable` seems correct, although I would use `bool` as the return type instead of `int`:

https://github.com/python/cpython/blob/efe7d08d178a7c09bcca994f2068b019c8633d83/Lib/logging/__init__.py#L817-L827

**Comment by jenstroeger** [comment]
I’d like to reopen this discussion because I have a class
```python
class FooFilter:

    # A few additional class variables and helper functions go here, i.e. a stateful class.

    def filter(self, record: logging.LogRecord) -> bool:
        ...
```
Like @Akuli reported above, so do I get the error:
```
error: Argument 1 to "addFilter" of "Filterer" has incompatible type "FooFilter"; expected "Union[Filter, Callable[[LogRecord], bool]]"  [arg-type]
```
The documentation states [here](https://docs.python.org/3/library/logging.html#logging.Filter):

> You don’t actually need to subclass `Filter`: you can pass any instance which has a `filter` method with the same semantics.

which is incorrect for typed code and the [current version](https://github.com/python/typeshed/tree/571cc6d77ad85c6b3c12f546f8b62c69f37da402) of type hints.

I now have two alternatives to fix this:

1. Inherit from [`logging.Filter`](https://docs.python.org/3/library/logging.html#logging.Filter):
    ```python
    class FooFilter(logging.Filter):
        ...
    ```
2. Implement this class as a callable:
    ```python
    class FooFilter:
        def __call__(self, record: logging.LogRecord) -> bool:
            return self.filter(record)
        ...  # And the rest.
    ```
In both cases I have to touch the implementation itself.

However, if we’d declare a [`Protocol`](https://docs.python.org/3/library/typing.html#typing.Protocol) 
```python
class FilterProtocol(Protocol):
    def filter(self, record: logging.LogRecord) -> bool:
        ...
```
and add that to the `addFilter()` signature, then we wouldn’t have to touch existing filter classes:
```python
_FilterType: TypeAlias = Filter | Callable[[LogRecord], bool] | FilterProtocol 
```
Would you be open to a PR?

**Comment by srittau** [comment]
Yes, it seems the PR only fixed part of this issue. I haven't looked into it yet, but from reading the discussion, your suggestion looks good. (But the protocol name should start with an underscore, as it's not available at runtime.)
