### ISSUE TITLE
Should http.client.HTTPMessage be subtype of Mapping[str, str]?

### ISSUE THREAD

**Issue by Unrud** [python/typeshed#5729]
Example:

[`URLopener.http_error`](https://github.com/python/typeshed/blob/f0bf6eebbde0f779666f17e258fceb78dbb7f9d5/stdlib/urllib/request.pyi#L295-L296) has the argument `headers: Mapping[str, str]`. It gets called with the value of [`HTTPResponse.msg`](https://github.com/python/cpython/blob/fe847a62852c3baaec6c97a5e2e7b2e66732bdb8/Lib/urllib/request.py#L1958-L1960) which has the type [`HTTPMessage`](https://github.com/python/typeshed/blob/d68701c0ecea1530fa768c406b189e5201c159bc/stdlib/http/client.pyi#L98).

**Comment by srittau** [comment]
Since `HTTPMessage` does not derive from `Mapping` at runtime and is also not registered as implementing `Mapping`, it shouldn't be one in stubs either. See some related discussion in #3576. In my opinion, the correct fix is to add a `MappingLike` protocol to `_typeshed` and use that for the `headers` argument.

**Comment by Akuli** [comment]
I don't think `MappingLike` should go to `_typeshed`, because the meaning of "mapping-like" depends on the code that uses it. For example, it could mean "has `.items()` method", "gives keys when iterating and values from `.__getitem__()`", or "has `.keys()` and `.__getitem__()`. A single protocol can't cover it all. We already have `SupportsItems`, `SupportsKeysAndGetItem` and a couple other classes, so we should just use those.

**Comment by Unrud** [comment]
Fixed in 9bba8a4b83b8d209f227c473b439bd6851c51562
