### ISSUE TITLE
I changed the GH Actions setting

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#5757]
FYI, I changed https://github.com/python/typeshed/settings/actions to not require approval for first-time contributors who aren't new to GitHub. See https://github.blog/changelog/2021-07-01-github-actions-new-settings-for-maintainers/ for background. If anyone disagrees with this we can discuss it.

**Comment by Akuli** [comment]
To me this seems like a "let's see how it goes" thing. Previously we haven't received any pull requests with the intent of abusing our CI, at least not after I became a maintainer, but that could be just because we needed to click a button to run the CI, and we would likely have noticed a malicious PR.
