### ISSUE TITLE
What type hints should I use for `re.compile`, `re.search` and `re.match` in common case?

### ISSUE THREAD

**Issue by ri-gilfanov** [python/typeshed#5761]
I have seen type hints for module `re` (https://github.com/python/typeshed/blob/master/stdlib/re.pyi).

I have seen a similar issue (https://github.com/python/typeshed/issues/3671).

However, I don't quite understand why the example below does not pass the type check. Thanks.

**Example**
```python
import re
from typing import AnyStr


class RegExpChecker:
    def __init__(self, pattern: AnyStr):
        self.pattern: re.Pattern[AnyStr] = re.compile(pattern)

    def __call__(self, string: AnyStr) -> bool:
        return bool(re.search(self.pattern, string))
```
**MyPy output**
```
example.py:7: error: Argument 1 to "compile" has incompatible type "str"; expected "AnyStr"
example.py:7: error: Argument 1 to "compile" has incompatible type "bytes"; expected "AnyStr"
example.py:10: error: Cannot infer type argument 1 of "search"
Found 3 errors in 1 file (checked 1 source file)
```
**Environment**
* Python v3.9.5
* Mypy v0.910

**Comment by srittau** [comment]
`AnyStr` is a type variable, if using Python 3, you probably want to use `str` instead of it. Otherwise, you'd need to make `RegExpChecker` generic over `AnyStr` to support both `str` and `bytes`.

**Comment by Akuli** [comment]
Maybe I should clarify this a bit.

Currently `AnyStr` is mentioned only in the arguments of `__init__` and `__call__`. These are two separate "instances" of `AnyStr` that don't have to be related to each other. It would be valid to do `RegExpChecker(b"lol").__call__("wut")`, for example; then `__init__`'s `AnyStr` would be `bytes` while `__call__`'s `AnyStr` would be `str`.

If you want the entire class to use the same type for `AnyStr`, so that this can't happen, you need:

```python
from typing import Generic

class RegExpChecker(Generic[AnyStr]):
    ...
```

Now `AnyStr` anywhere inside `class RegExpChecker` has a different meaning: it's no longer specific to each method, but it's the `AnyStr` of the whole class. So if you do `RegExpChecker(b"lol")`, it will be `bytes`, and `RegExpChecker(b"lol").__call__` will also expect a `bytes` argument.

**Comment by ri-gilfanov** [comment]
@srittau and @Akuli, thank you for the help.
