### ISSUE TITLE
Incorrect type annotation for _SimpleStrainable

### ISSUE THREAD

**Issue by ethanscorey** [python/typeshed#5809]
Currrently, the `_SimpleStrainable` type alias is defined as `Union[str, bool, None, bytes, Pattern[str], Callable[[str], bool]]`, but this definition is incorrect and causes mypy to raise an error when type-checking a line like:
`soup.find_all(lambda tag: tag.has_attr('href'))`

Per the BeautifulSoup documentation (and its source code), `.find_all`'s `name` parameter can accept a callable that take a `Tag` as its only argument and returns a boolean. That's what makes the line of code above work. If it could only accept callables that take strings as their argument, the code above would raise an `AttributeError`. 

Thus, shouldn't the `_SimpleStrainable` type alias be defined as `Union[str, bool, None, bytes, Pattern[str], Callable[[Union[str, Tag]], bool]]`?

**Comment by JelleZijlstra** [comment]
Oops, that's probably my bad.

Your suggested solution is problematic though, because a `Callable[[Union[str, Tag]], bool]` in an argument position would have to accept *both* str and Tag arguments because of contravariance. Instead, there should perhaps be separate entries for `(str) -> bool` and `(Tag) -> bool`. Or perhaps I just made up the str variant and we can remove the str variant entirely.

**Comment by ethanscorey** [comment]
Ah, okay, I always find co/contravariance confusing. It does look like `_SimpleStrainable` needs to include `Callable[[str], bool]` as well as `Callable[[Tag], bool]`, since you can pass a callable that tests a string to the `SoupStrainer` constructor's `name` parameter. 

Thanks for the quick response!

**Comment by JelleZijlstra** [comment]
Sounds good, do you want to submit a PR?

Perhaps we need to split this alias if in some contexts it can accept a Tag and in others a str. That may be too complicated though.

**Comment by JelleZijlstra** [comment]
Fixed by #5810
