### ISSUE TITLE
print's flush keyword argument should be int

### ISSUE THREAD

**Issue by ianfun** [python/typeshed#5832]
**Whether output is buffered is usually determined by file, but if the flush keyword argument is true, the stream is forcibly flushed.[link](https://docs.python.org/3/library/functions.html#print)**
mypy show errors when I use `print(flush=1)`
```
error  mypy:arg-type  Argument "flush" to "print" has incompatible type "int"; expected
                             "bool"
```
but is it OK to use `print(flush=1)`

in [builtins.pyi](https://github.com/python/mypy/blob/master/mypy/typeshed/stdlib/builtins.pyi#LC1225) 
 *flush*  keyword argument is type `bool`
Does *flush*  keyword argument need to change to `int`?

**Comment by JelleZijlstra** [comment]
Transferred this issue to typeshed because it's purely a problem with the stubs.

I'm not inclined to change anything here. It's true that passing an int works at runtime, but so does passing a string (`print(flush="x")` doesn't throw). The argument is clearly boolean in intent, and it servers users better to type it as bool.

**Comment by srittau** [comment]
Closing per Jelle's comment. This is clearly intended to be a boolean and warning about it not being one can catch potential type issues.
