### ISSUE TITLE
Deprecated `threading` aliases

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#6494]
The `threading` module has a number of camelCase aliases for snake_case functions and methods. All of these aliases are deprecated, and have been for a long time. The typeshed stub includes some of these aliases, but not all of them:

---

**Included in typeshed stub**
-  `currentThread`
- `Thread.getName`
- `Thread.setName`
- `Thread.isDaemon`
- `Thread.setDaemon`
- `Condition.notifyAll`

**Not included in typeshed stub**
- `activeCount`
- `Event.isSet`

---

A few things occur to me:

1. typeshed should probably either include all of these in the stub, or none of them.
2. There's a bit of a tension here between different uses of typeshed. From a type-hinting perspective, it would probably be good to have these in the stub. From an autocompletion perspective, however, we probably don't want editors/IDEs suggesting these aliases when users hit Tab.
3. If it's decided that typeshed should include these in the stub, we should add comments to mark that they're deprecated.

---

Thoughts? 🙂

**Comment by sobolevn** [comment]
I would love to wave `Deprecated[]` type as a part of our typesystem at some point 🙁

**Comment by srittau** [comment]
In general, we should not remove functions, just because they are deprecated. Users may still rely on them. (Although marking them as such in the stubs is a good idea. And `Deprecated[]` or `@deprecated` would be nice to have.) On the other hand, I would not actively add deprecated functions, unless someone asks for them.
