### ISSUE TITLE
requests.packages missing in types-requests 2.27.5

### ISSUE THREAD

**Issue by wpwood** [python/typeshed#6893]
When moving from types-requests 2.26.3 to 2.27.5, the following code
```
requests.packages.urllib3.disable_warnings(requests.packages.urllib3.exceptions.InsecureRequestWarning)
```

 now gets a type error in mypy, `error: Module has no attribute "packages"`

I was able to fix the issuing by forcing mypy to use types-requests 2.26.3.

**Comment by JelleZijlstra** [comment]
We removed it in #6859. That PR doesn't make clear why the copy in `requests` was removed; it seems to still exist in the most recent release of requests.

**Comment by wpwood** [comment]
> We removed it in #6859. That PR doesn't make clear why the copy in `requests` was removed; it seems to still exist in the most recent release of requests.

Yeah, that was what I saw as well, that it still seems to be in `requests`.

**Comment by srittau** [comment]
The original plan was to import the urllib3 stubs from `types-urllib3` into `requests.packages.urllib3` as runtime does. Unfortunately, this isn't easily possible. The `requests.packages.urllib3` were quite outdated, and it's not clear which version of `urllib3` we should use. It would also mean that we have to maintain two copies of urllib3. I recommend to import urllib3 imports directly from `urllib3` instead of `requests.packages.urllib3`.

**Comment by Akuli** [comment]
The code example in this issue needs the same copy of urllib3 as requests uses internally, because it is suppressing a warning that requests generates while it is using its urllib3. I think we should add back `requests/packages/__init__.pyi` with a `__getattr__` incomplete marker, so that the import will at least work, even if it isn't very nicely type checked.

**Comment by srittau** [comment]
The `__getattr__()` marker is a good idea. The alternative is (your idea, I think) to basically copy the urllib3 structure and do a `from urllib.xyz import *` in each file, although I'd like to avoid that.

**Comment by andersk** [comment]
`requests` no longer vendors `urllib3` or any other packages as of 2.16.0 (psf/requests#4067), so there’s no longer a concern as to which version to use.

**Comment by srittau** [comment]
Closing per @andersk's comment.
