### ISSUE TITLE
Stub uploader failing

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#6956]
The stub uploader is currently failing (https://github.com/typeshed-internal/stub_uploader/runs/4859589146?check_suite_focus=true):
```
Uploading types_redis-4.1.0.0-py3-none-any.whl

  0%|          | 0.00/35.6k [00:00<?, ?B/s]
100%|██████████| 35.6k/35.6k [00:00<00:00, 201kB/s]
Error during upload. Retry with the --verbose option for more details.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
File already exists. See https://pypi.org/help/#file-name-reuse for more information.
```
This is probably because of #6952. The uploader apparently doesn't handle this case where we change the version number from .* to .0.

**Comment by Akuli** [comment]
It would be good to better validate versions in `check_consistent`.

**Comment by srittau** [comment]
This can't work with our current version logic, because the base version - to which the uploader's version gets appended - differs. When using `1.2.*`, the base is `1.2`, while the base version of `1.2.3` is  `1.2.3`. I don't have a good solution for this at the moment, except to introduce a new metadata field. But I'm not sure we need that extra complexity.

**Comment by JelleZijlstra** [comment]
Closing since the issue was fixed. We don't need to change the version logic for now, but we can open a new issue if we run into this problem more.
