### ISSUE TITLE
Should Sequence support __add__?

### ISSUE THREAD

**Issue by jamesbraza** [python/typeshed#6985]
The Python docs on Sequence mentions it supports concatenation [here](https://docs.python.org/3.8/library/stdtypes.html#common-sequence-operations).  The current `Sequence` ([link](https://github.com/python/typeshed/blob/1f000d28813d1a4720a67e4f282c00d0c904921b/stdlib/typing.pyi)) doesn't include `__add__`.

Please see the below code:

```python
from typing import Sequence

# Can add List
list_1: Sequence[int] = [1, 2]
list_2: Sequence[int] = [3, 4]
assert len(list_1 + list_2) == 4

# Can't add range
range_1 = range(5)
range_2 = range(6)
concatenated_ranges = range_1 + range_2
```

Running this code throws a `TypeError` on the last line:

```
Traceback (most recent call last):
  File "/path/to/foo.py", line 11, in <module>
    concatenated_ranges = range_1 + range_2
TypeError: unsupported operand type(s) for +: 'range' and 'range'
```

Running `mypy==0.931` on this I get the below errors:

```
path/to/foo.py:6:12: error: Unsupported left operand type for + ("Sequence[int]")  [operator]
path/to/foo.py:11:23: error: Unsupported left operand type for + ("range")  [operator]
Found 2 errors in 1 file (checked 21 source files)
```

I believe mypy is raising these errors per typeshed `Sequence` not implementing `__add__`.

So, there are two possibilities:
- Either: the [Python docs](https://docs.python.org/3.8/library/stdtypes.html#common-sequence-operations) should mention `__add__` isn't universally implemented for all `Sequence`
- Or `range` should implement `__add__` and we should add `Sequence.__add__` should be added to typeshed

What do you think?

**Comment by JelleZijlstra** [comment]
`range()` couldn't support `__add__`, because range objects can't be discontinuous. I guess it could return a list, but that could quickly eat a lot of memory and it would be inconsistent with other sequences.

Also, even sequences that do support `__add__` only support adding their own type; you can't do list + tuple. That makes it not very useful in the typing world: if you see `a: Sequence; b: Sequence; a + b`, you can't know whether the `+` is safe because you don't know the concrete types of `a` and `b`.

There is tension between the informal notion of "sequence" in the Python documentation, which can mean slightly different things depending on context, and the precise notion of a Sequence in typing, which defines an exact set of supported methods. At the C level, a sequence (according to https://docs.python.org/3/c-api/sequence.html#c.PySequence_Check) just needs to support `__getitem__`.

The Python docs link you link already say (in footnote 7 to the table) that `range` doesn't support `*` or `+`.

**Comment by jamesbraza** [comment]
That makes a ton of sense, I realize now it doesn't make sense to change. Thank you for a detailed response @JelleZijlstra!
