### ISSUE TITLE
mypy is failing on the stdlib

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#7019]
CI is currently failing on all PRs with the following message from mypy:

`stdlib/email/message.pyi:13: error: Cannot determine type of "Any" [has-type]`.

E.g.:

- https://github.com/python/typeshed/pull/7018
- https://github.com/python/typeshed/pull/7017

mypy appears to be failing on all platforms, but only on Python 3.8+.

I can also reproduce this error locally. No idea what's changed to make it suddenly start erroring as part of the CI checks, though.

**Comment by hauntsaninja** [comment]
Change of Python version from 3.10.1 to 3.10.2, maybe?

**Comment by AlexWaygood** [comment]
> Change of Python version from 3.10.1 to 3.10.2, maybe?

But it's also failing on 3.8!

**Comment by hauntsaninja** [comment]
That's just the version that's being passed to mypy. In all cases, mypy is running on Python 3.10. I'm guessing there's an `ast` regression, which is why we don't see it in 3.7 and below (where mypy does not use `ast`)

**Comment by AlexWaygood** [comment]
> That's just the version that's being passed to mypy. In all cases, mypy is running on Python 3.10. I'm guessing there's an `ast` regression, which is why we don't see it in 3.7 and below (where mypy does not use `ast`)

Ah, gotcha.

**Comment by hauntsaninja** [comment]
Hmm, I can repro locally on 3.9.9 so that's probably not it.

Bad:
<img width="1036" alt="Screen Shot 2022-01-24 at 02 00 58" src="https://user-images.githubusercontent.com/12621235/150761898-1880c887-71c8-4222-ba10-ac381fdcd944.png">

Good:
<img width="1033" alt="Screen Shot 2022-01-24 at 02 01 05" src="https://user-images.githubusercontent.com/12621235/150761866-13cca7bf-7f5f-40a6-b704-50013b9f9ed6.png">

**Comment by hauntsaninja** [comment]
So weird. Thanks both for getting things green. I'd also welcome any hypotheses :-)
