### ISSUE TITLE
codecs.open() result can't be used as a file

### ISSUE THREAD

**Issue by rwbarton** [python/typeshed#732]
This program seems to be okay (in both Python 2 and 3), but the stubs don't allow it.
```py
import codecs

f = codecs.open('/tmp/a.txt', mode='w', encoding='utf-8')
f.write('hi\n')  # error: "StreamReaderWriter" has no attribute "write"
f.close()  # error: "StreamReaderWriter" has no attribute "close"
```
I'm not sure exactly what changes should be made, but it seems like the result of `open` ought to be a subtype of `IO`.

**Comment by JelleZijlstra** [comment]
`codecs.open` returns a `StreamReaderWriter`, which has a very incomplete stub in current typeshed:

```
class StreamReaderWriter:
    def __init__(self, stream: BinaryIO, Reader: _stream_reader_type, Writer: _stream_writer_type, errors: str = ...) -> None:
        ...
```
The Python 3 stub has just this, the Python 2 one adds `__enter__` and `__exit__`.

There's a couple of things here that may require changes:
* There are separate Python 2 and Python 3 stubs for the codecs module, but the API is pretty much the same. They should be merged; there are already some differences that appear to be just from people making changes to one but not the other.
* `StreamReaderWriter.__enter__` in Python 2 is currently annotated as returning `BinaryIO`, but it actually returns a `StreamReaderWriter`.
* `StreamReaderWriter` should probably inherit from `typing.IO`. This isn't quite accurate because it's missing some methods from `typing.IO` (e.g. `truncate`), but it's probably close enough. `codecs.StreamRecoder` already inherits from `BinaryIO` even though it's missing a similar set of methods. I would like to make `StreamReaderWriter` inherit from `TextIO`, but I guess that would be wrong for bytes-to-bytes encodings.

I think I'll first submit a PR merging the Python 2 and 3 stubs, then make the other changes.

**Comment by JelleZijlstra** [comment]
Actually, going to roll back `StreamReaderWriter.__enter__` to `BinaryIO` for now since this will probably break some existing code otherwise. I'll save cleaning that up for another PR.
