### ISSUE TITLE
What's the point of having stubs where types are mostly missing or Any ?

### ISSUE THREAD

**Issue by anentropic** [python/typeshed#7457]
e.g.
https://github.com/python/typeshed/blob/607aa37ee9a5c380baedb4938148fb3280f833e3/stubs/babel/babel/numbers.pyi#L15
(but have a look at the whole file, there's hardly any substantive type annotations)

I installed `types-babel`

this suppresses mypy errors like "Skipping analyzing "babel.numbers": module is installed, but missing library stubs"

but otherwise doesn't seem to provide much value, am I missing something?

now instead I get "Call to untyped function "get_currency_symbol" in typed context" error

...either way I have to mark some code as ignored or toggle off a category of checks

**Comment by anentropic** [comment]
same problem with `types-stripe`

https://github.com/python/typeshed/blob/607aa37ee9a5c380baedb4938148fb3280f833e3/stubs/stripe/stripe/api_resources/abstract/createable_api_resource.pyi#L8

**Comment by AlexWaygood** [comment]
Hi! Stubs like these could indeed be improved. PRs to improve them are very welcome :)

typeshed is a pretty huge repository, and maintained by a _fairly_ small group of volunteers in our free time. Rather than try to make stub files perfect before committing them, we generally take the view that it's better to have "some imperfect stubs" rather than "no stubs at all". For example, in `babel.numbers.get_currency_symbol`, it's true that a type checker won't know anything about what the parameter types are meant to be. But a type checker will still raise an error if you try to pass in the wrong number of arguments, or use a keyword argument that doesn't apply. That's a lot more than you'd get if you simply `# type: ignore`d the `Skipping analyzing "babel.numbers": module is installed, but missing library stubs` error. And it creates a baseline on which we can build in future PRs.

If you think you can find the time to help improve these stubs, please submit a PR, and we will review it!

**Comment by srittau** [comment]
@AlexWaygood put it well. I don't think there's anything actionable for us to do here, so I'm closing this.

**Comment by anentropic** [comment]
Hi, thanks that answers the question - I wasn't sure if they were intended to stay as empty placeholders for some reason that I didn't understand

**Comment by anentropic** [comment]
Is there a documentation explaining how versioning of typeshed stubs vs target library versions is managed?

**Comment by AlexWaygood** [comment]
Lots of details here: https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-stubs

**Comment by srittau** [comment]
> Hi, thanks that answers the question - I wasn't sure if they were intended to stay as empty placeholders for some reason that I didn't understand

Any improvements welcome! Unannotated fields should generally be annotated, in fact that's a placeholder for us to say: "Please annotate me!"
