### ISSUE TITLE
(🐞) `NoReturn`, `Never`, `Self` and `TypeAlias` are not subscriptable

### ISSUE THREAD

**Issue by KotlinIsland** [python/typeshed#7507]
```py
from typing import NoReturn

a: NoReturn[int]
b = NoReturn[int]
```

These methods do exist, but are no-ops that just raise exception.

**Comment by TeamSpen210** [comment]
That’s correct, [`NoReturn`](https://docs.python.org/3.11/library/typing.html#typing.NoReturn) is a special value that accepts no parameters. It represents a function that never returns - looping forever or always raising an exception. It’s also used to indicate a type which has no possible valid value, kinda like an empty union.

The problem is actually that mypy isn’t giving an error.

**Comment by KotlinIsland** [comment]
Actually the stubs are wrong, they state that it has a `__getitem__` method

**Comment by srittau** [comment]
Strictly speaking, these have `__getitem__()` methods, only that these raise a `TypeError` when called. I don't have good solution for this. We could introduce a `_SpecialForm` sub-class that annotates `__getitem__()` with `NoReturn`, but that would make the mro of these item not match runtime.

**Comment by KotlinIsland** [comment]
Are fake base classes against the style of typeshed? Do they cause a lot of issues?

**Comment by AlexWaygood** [comment]
`Any` is already understood by mypy to not be subscriptable.

https://github.com/python/typeshed/blob/e8286e7048aeeced78c24d6d38bf49e5b92ddf88/stdlib/typing.pyi#L467

**Comment by KotlinIsland** [comment]
@srittau BTW, why is `TypedDict` not a special form?
```py
    # TypedDict is a (non-subscriptable) special form.
    TypedDict: object
```

**Comment by KotlinIsland** [comment]
I can't see any possible solution to this using stubs, I've raised it here: python/mypy/issues/12375
