### ISSUE TITLE
`gettext.GNUTranslations.__init__`’s argument has an incorrect type

### ISSUE THREAD

**Issue by Jayman2000** [python/typeshed#7628]
`mypy` says that this program is wrong:

```python
from gettext import GNUTranslations

with open("foo.mo", mode='rb') as mo_file:
    GNUTranslations(mo_file)
```

`mypy`’s output:

```
main.py:4: error: Argument 1 to "GNUTranslations" has incompatible type "BufferedReader"; expected "Optional[IO[str]]"
Found 1 error in 1 file (checked 1 source file)
```

I believe that `fp` (`gettext.GNUTranslations.__init__`’s argument) should have the type `Optional[IO[bytes]]`, not `Optional[IO[str]]`.

**Comment by TeamSpen210** [comment]
The problem is that `NullTranslations` (its base class) is hinted as taking an `IO[str] | None`, but `GNUTranslations` needs a binary file. `NullTranslations` doesn't actually do anything with the file, just store it for subclasses to use so the best solution would probably be to make `NullTranslations` take `IO | None` and then constrain in `GNUTranslations`.

**Comment by srittau** [comment]
I'd say we just type `NullTranslations` according to how we type `GNUTranslations` (as long as it doesn't contradict the actual implementation in the former) as the latter is the only "real" translations class we have. We also should replace `IO` with a tight protocol.
