### ISSUE TITLE
paramiko channel.setblocking() argument type doesn't match the docs

### ISSUE THREAD

**Issue by madscientist** [python/typeshed#7697]
According the paramiko docs, channel.setblocking() takes an integer 0 or 1:
https://docs.paramiko.org/en/stable/api/channel.html#paramiko.channel.Channel.setblocking

According to typeshed channel.pyi it takes a bool:
https://github.com/python/typeshed/blob/2299c43860c7115fabfd14ad854144e2ef20e132/stubs/paramiko/paramiko/channel.pyi#L72

This is causing my code, written to the docs, to throw mypy errors.  The implementation doesn't care:
```
        if blocking:
            self.settimeout(None)
        else:
            self.settimeout(0.0)
```

I guess either the docs should be changed, or the typeshed .pyi file should be updated...

Thanks for your work!

**Comment by Akuli** [comment]
Feel free to make a PR that changes it to `bool | Literal[0, 1]`. Passing in an integer that could be something else than 0 or 1 is likely a mistake, so `bool | int` (which in fact would be equivalent to just `int`) wouldn't be great.

In general, pretty much any function taking in a `bool` will in practice work with a lot of other types too, and type checkers will complain about it because it's likely a mistake. But in this case accepting 0 and 1 makes sense, because the documentation uses 0 and 1.

**Comment by madscientist** [comment]
Agreed; if it wasn't called out like that in the paramiko docs I would just change my uses to True/False and call it a day.  But I'm wary of this because it's so clearly specified in the docs that the value should be 0 or 1, even though the current implementation doesn't care.

Probably it's really a paramiko doc issue, but...  OK thanks.
