### ISSUE TITLE
pow float return value is Any in 0.950

### ISSUE THREAD

**Issue by TylerYep** [python/typeshed#7733]
**Bug Report**

I upgraded to mypy 0.950 today and ran into the following error involving function return types:

**To Reproduce**

```
# x.py
def fn(x: float = 8.9) -> float:
    return 2 ** x    # error: Returning Any from function declared to return "float"  [no-any-return]
```

**Expected Behavior**

Expected this to pass cleanly.

**Actual Behavior**

I'm not sure why this now returns Any.

**Your Environment**

- Mypy version used: 0.950
- Mypy configuration options from `mypy.ini` (and other config files): strict = True
- Python version used: Python 3.10.0
- Operating system and version: Mac OSX

**Comment by Akuli** [comment]
`int ** float` can be a complex number, if the int is negative.

```
>>> (-1) ** 2.3
(0.587785252292474+0.8090169943749468j)
```

But this doesn't happen for `2 ** float`, or for any other positive number instead of 2:

```
>>> 2 ** (-3.4)
0.09473228540689989
```

`0 ** float` behaves a bit surprisingly, and I don't think we should handle it specially in the stubs. In practice, the `0` is very unlikely to be specified in a way where the type checker can infer its type to be `Literal[0]`.
