### ISSUE TITLE
median_grouped() returns a float

### ISSUE THREAD

**Issue by rhettinger** [python/typeshed#7824]
There was a bug in *median_grouped()* that allowed the output type for match in the input type for iterables of length one.  Otherwise, it always returned a float.

    def median_grouped(data: Iterable[_NumberT], interval: _NumberT = ...) -> _NumberT: ...

That bug was fixed.  The input types are anything convertible to a float and the output is always a float.

**Comment by hauntsaninja** [comment]
Thanks for filing this! Looks like this is https://github.com/python/cpython/pull/92533 and is so far only on the 3.12 branch (since we'll probably want to version gate the change to the stub)

**Comment by JelleZijlstra** [comment]
The stub is also incorrect for previous versions, since as @rhettinger said, it always returns a float for iterables of length >1. On 3.9:

```
In [39]: statistics.median_grouped([1, 2, 3])
Out[39]: 2.0

In [40]: statistics.median_grouped([1])
Out[40]: 1
```

We can't express that precisely in the type system. The safest thing to do would be to return `float | _NumberT`. Usually we avoid union return types, but in this case it seems fairly harmless:
- `_NumberT` is defined as `_NumberT = TypeVar("_NumberT", float, Decimal, Fraction)`
- So users who pass iterables of floats (or ints) will just see `float` as the return type
- Users who pass Decimals or Fractions will see `float | Decimal`, but that's fairly rare, and since the types are mostly compatible it shouldn't be as bad as other union return types.

So I propose that we make the stub return `float` on 3.12 and `_NumberT | float` before 3.12.

**Comment by rhettinger** [comment]
> So I propose that we make the stub return float on 3.12 

Do you mean 3.11?

The bug fix is already in and will show-up in 3.11b2.

**Comment by JelleZijlstra** [comment]
It's not actually in the 3.11 branch. It sounds like you want it to be, so I triggered the backport.

**Comment by rhettinger** [comment]
Thanks.
