### ISSUE TITLE
add build-backend to pyproject.toml

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [python/typeshed#7850]
Could you add add build-backend to pyproject.toml?

**Comment by srittau** [comment]
What purpose would that have? typeshed is not "built" in the traditional sense, there is no "typeshed" package.

**Comment by Alessandro-Barbieri** [comment]
I see that the generated types-* packages aren't using PEP517

**Comment by srittau** [comment]
Indeed, we are using a separate project to build those: https://github.com/typeshed-internal/stub_uploader. Currently, the script there calls setuptools programatically, although at some point we could look into converting that to PEP 517. But the current setup works and changing it would be rather complicated.

**Comment by AlexWaygood** [comment]
I'm closing this issue:

- No compelling reason has been given to make this change.
- The status quo appears to work fine as far as I can see, and changing it might be complicated.
- Any change should probably be tracked over at https://github.com/typeshed-internal/stub_uploader anyway, rather than on the typeshed issue tracker.
