### ISSUE TITLE
Return types of `XMLPullParser.read_events` and `iterparse` from `xml.etree.ElementTree`

### ISSUE THREAD

**Issue by Prometheus3375** [python/typeshed#8039]
`typeshed` assigns return type for [`iterparse`](https://github.com/python/typeshed/blob/master/stdlib/xml/etree/ElementTree.pyi#L264) as `Iterator[tuple[str, Any]]` and for [`XMLPullParser.read_events`](https://github.com/python/typeshed/blob/master/stdlib/xml/etree/ElementTree.pyi#L272) as `Iterator[tuple[str, Element]]`.

Internally, `iterparse` uses `XMLPullParser` and then yields from `XMLPullParser.read_events`. But `iterparse` returns a special iterator object which has a nullable `root` attribute.

`XMLPullParser.read_events` itself returns tuples with different 2nd object depending on the event. From [docs](https://docs.python.org/3.10/library/xml.etree.elementtree.html#xml.etree.ElementTree.XMLPullParser.read_events):
```
start, end: the current Element.
comment, pi: the current comment / processing instruction
start-ns: a tuple (prefix, uri) naming the declared namespace mapping.
end-ns: None (this may change in a future version)
```

At now, the presence of `root` attribute of `iterparse` result is not documented ([issue](https://github.com/python/cpython/issues/93607)), so I suggest to ignore it and simply use `Iterator[T]` as return type for both `XMLPullParser.read_events` and `iterparse`.

I propose several variants for `T`:
```python
tuple[str, Any]
```
```python
tuple[str, Element | tuple[str, str] | None]
```
```python
tuple[Literal['start', 'end', 'comment', 'pi'], Element] | \
    tuple[Literal['start-ns'], tuple[str, str]] | \
    tuple[Literal['end-ns'], None]
```

I am not sure which one is better for type checkers.

**Comment by AlexWaygood** [comment]
In general, we prefer to avoid union return types in typeshed: see https://github.com/python/mypy/issues/1693 for some detailed discussion. They end up being annoying for end users due to the number of checks they have to perform on the returned object in order to precisely narrow the type. So -- while I'm far from an expert on the `xml` modules -- I would guess that `Iterator[tuple[str, Any]]` would probably be the return type least likely to cause false-positive errors.

**Comment by AlexWaygood** [comment]
Feel free to create a PR! :)
