### ISSUE TITLE
[Bug] `tqdm(iterable)` edge case is not correct

### ISSUE THREAD

**Issue by alkatar21** [python/typeshed#8296]
This is probably not the normal case, but I have the following construct of an iterator which is currently not recognized as an iterable and therefore is not inferring correctly.

Related to #8235 @AlexWaygood (Not sure whether pinging is okay?)

Python 3.8.10
pylance v2022.7.31 (first time tqdm stubs included)

```py
# pyright: strict
"""Docs."""
from __future__ import annotations
from tqdm import tqdm

class Item:
    def __next__(self) -> Item: ...

class Test:
    def __iter__(self) -> Item: ...

test = Test()
for i in tqdm(test):  # Argument of type "Test" cannot be assigned to parameter "iterable" of type "None" in function "__init__"
    pass
```
![grafik](https://user-images.githubusercontent.com/61387986/179030872-eb308009-702f-41d9-a124-02312fc12254.png)

**Comment by AlexWaygood** [comment]
Hmm, I'd guess pylance does not infer `Test` as being a subtype of `typing.Iterable` because `Iterable`s are supposed to return `Iterator`s from their `__iter__` methods, and `Iterator`s are themselves supposed to define `__iter__` methods. But `Test` returns `Item` from its `__iter__` method, and `Item` does not define `__iter__`, ergo `Item` is not an `Iterator`, ergo `Test` does not return an `Iterator` from its `__iter__` method, ergo `Test` is not an `Iterable`, ergo pyright declines to pick the first overload in `tqdm.std.tqdm.__init__`, and then emits this error.

**Comment by AlexWaygood** [comment]
Could you confirm whether this fixes it? And would you see that as an acceptable solution?

```python
# pyright: strict
"""Docs."""
from __future__ import annotations
from tqdm import tqdm
from typing_extensions import Self

class Item:
    def __next__(self) -> Item: ...
    def __iter__(self) -> Self:
        return self

class Test:
    def __iter__(self) -> Item: ...

test = Test()
for i in tqdm(test):  # Argument of type "Test" cannot be assigned to parameter "iterable" of type "None" in function "__init__"
    pass
```

**Comment by alkatar21** [comment]
Without tqdm, pyright is fine with the code:
```py
for i in test:
    pass
```

Your code snippet removes the pyright message, but mypy complains about Self is not a valid type (in 3.8 I think?).

I am not sure if I understand it correctly with acceptable solution. Is the question whether I can adjust the code? Then the answer is not really, because the class comes from a library and this is only a minimal example here.

**Comment by Akuli** [comment]
Arguably the library is broken, because an iterator should define an `__iter__` method that returns the iterator itself. Without `__iter__`, type checkers don't treat `Item` as an iterator, and so they don't treat `Test` as an iterable. This has been discussed before, too: https://github.com/python/typeshed/issues/6030

For now, the best workaround (without changing the library) is probably casting `test` to an iterable:

```python3
from typing import Iterable
...
test = Test()
for i in tqdm(cast(Iterable[Item], test)):
    pass
```

**Comment by Akuli** [comment]
I confirmed that casting to `Iterable[Item]` works. If something is still unclear, feel free to ask :)
