### ISSUE TITLE
Wave stdlib parameter regression in mypy 0.950

### ISSUE THREAD

**Issue by f4hy** [python/typeshed#8322]
**Bug Report**

When working with the `wave` module of the standard library, valid code from mypy <0.950 works but errors with 
```error: Argument 1 to "setparams" of "Wave_write" has incompatible type "waveparams"; expected "_wave_params"``` 
on 0.950+
**To Reproduce**

Using Example code 
```python
# bug_report.py
import wave
import collections

waveparams = collections.namedtuple(
    "waveparams",
    "nchannels, sampwidth, framerate, nframes, comptype, compname",
)

with wave.open("test.wav", "wb") as wav_file:
    params = waveparams(
        nchannels=1,
        sampwidth=2,
        framerate=16_000,
        nframes=0,
        comptype="NONE",
        compname="NONE",
    )
    wav_file.setparams(params)
```
running `mypy` an older version (say 0.931) it says no issues. but using a fully up to date version throws and error of
`error: Argument 1 to "setparams" of "Wave_write" has incompatible type "waveparams"; expected "_wave_params"`

I am not sure why they would be 'incompatible' here. My team was making a namedtuple to make up for the fact that wav_file.setparameters just took a raw untyped tuple as input. 

**Expected Behavior**

The named tuple here does match the required fields ofr setparams of `Wave_write` object from the stdlib so it should pass.

**Actual Behavior**

On newer versions of mypy this errors

**Your Environment**

- Python version used: 3.8
- Operating system and version: Linux

**Comment by hauntsaninja** [comment]
The stub in typeshed does not have `wav_file.setparams` defined as taking an anonymous tuple.
It has it taking `wave._wave_params`, which is a namedtuple, as defined here: https://github.com/python/cpython/blob/c961d14f85a0e3e53d5ad1182206ef34030f10b8/Lib/wave.py#L89

Type checkers treat your waveparams as incompatible with `wave._wave_params` since e.g. `isinstance(waveparams(...), wave._wave_params)` is False.

The reason mypy's behaviour changed is because of https://github.com/python/typeshed/pull/7000
Previously, `wave.open` would just return `Any`. Now it returns a more accurate type if it can.
This explains why your code was accepted, since you can do basically anything you want to `Any`, e.g. `wav_file.setpardfsdfaljlkvams(params)`.

That said, the actual implementation of setparams doesn't need params to be `wave._wave_params`, so this is a false positive and typeshed should loosen its stub to accept anonymous tuples as well: https://github.com/python/cpython/blob/c961d14f85a0e3e53d5ad1182206ef34030f10b8/Lib/wave.py#L516

**Comment by f4hy** [comment]
I actually think the stdlib should make `_wave_params` not private, and rename it to `wave_params` maybe.

**Comment by hauntsaninja** [comment]
Currently, yes, your best option is to use the private namedtuple.

However, like I said, typeshed can and should make a change to allow other tuples to setparams.

I'm inclined to agree that the stdlib should make it public, try your luck over at github.com/python/cpython ?

**Comment by f4hy** [comment]
Thanks for the anonymous tuple support in the typeshed. I still think the nicer solution is to update cpython : https://github.com/python/cpython/pull/94992 
But allowing just a tuple is a good stopgap.
