### ISSUE TITLE
GenericAlias not Callable, but it should be

### ISSUE THREAD

**Issue by mjog** [python/typeshed#8709]
[The docs for `GenericAlias`](https://docs.python.org/3/library/stdtypes.html#types-genericalias) explicitly state these objects are callable, giving the following example:

```
>>> t = list[str]
>>> t([1, 2, 3])
[1, 2, 3]
```

However the [definition is not marked as such](https://github.com/python/typeshed/blob/6e985ef3de3678676d753a1efbf45fd67095a3b2/stdlib/types.pyi#L580), and hence causes errors when type checking such cases, e.g. mypy will complain ""GenericAlias" not callable".

**Comment by AlexWaygood** [comment]
We discussed this in #6392, and decided it would probably cause more problems than it fixes to add `__call__` to `types.GenericAlias`,  since this class needs to be heavily special-cased by type checkers. If mypy reports that `t` is not callable, that's arguably a bug in mypy's special-casing for generic aliases, so should be reported to mypy.

**Comment by mjog** [comment]
It's a shame all type checkers and other uses of typeshed will need to each individually re-implement this.

Nevertheless, I opened an issue for mypy: https://github.com/python/mypy/issues/13637
