### ISSUE TITLE
SupportsAllComparisons and SupportsRichComparison as generic protocols

### ISSUE THREAD

**Issue by Kentzo** [python/typeshed#8964]
With `SupportsDunderLT`, `SupportsDunderGT`, `SupportsDunderGE`, `SupportsDunderLE` redefined as generic protocols with a contra variant type, wouldn't it make sense to also redefine [`SupportsAllComparisons`](https://github.com/python/typeshed/blob/dc7fdc6f5dc19935845eb407028ef86abe6c691a/stdlib/_typeshed/__init__.pyi#L65) and [`SupportsRichComparison`](https://github.com/python/typeshed/blob/dc7fdc6f5dc19935845eb407028ef86abe6c691a/stdlib/_typeshed/__init__.pyi#L69) as

```python
class SupportsAllComparisons(
    SupportsDunderLT[_T_contra],
    SupportsDunderGT[_T_contra],
    SupportsDunderGE[_T_contra],
    SupportsDunderLE[_T_contra],
    Protocol[_T_contra]
): ...

class SupportsRichComparison(
    SupportsDunderLT[_T_contra],
    SupportsDunderGT[_T_contra],
    Protocol[_T_contra]
): ...
```

**Comment by AlexWaygood** [comment]
Can you point to some stubs where you think this would bring benefits over the existing definitions?

---

As an aside: `SupportsRichComparison` is currently a union of two protocols:

https://github.com/python/typeshed/blob/8d941f0e53f5c4ff7a376c439720eb9e96aa6742/stdlib/_typeshed/__init__.pyi#L69

As well as making the type generic, you also seem to be proposing to change it from being a union of two protocols to being a subclass of the two protocols. That would have very different semantics.

Currently, when we use it (for example) in this overload for `builtins.max()`, it's to indicate "the `key` parameter can be a function that returns something with a `__lt__` method, or it can be a function that returns something with a `__gt__` method". If `SupportsRichComparison` were defined as a subclass of the two protocols instead of a union, the contract specified in this overload would be very different. It would be "the `key` parameter can be a function that returns an object that has both a `__lt__` method and a `__gt__` method":

https://github.com/python/typeshed/blob/8d941f0e53f5c4ff7a376c439720eb9e96aa6742/stdlib/builtins.pyi#L1396-L1397

**Comment by AlexWaygood** [comment]
Closing for now, but happy to reopen if you can give me an example of where this would be useful :)
