### ISSUE TITLE
bytes broader than bytearray?

### ISSUE THREAD

**Issue by gsakkis** [python/typeshed#8970]
Mypy errors with `Overloaded function signature 2 will never be matched: signature 1's parameter type(s) are the same or broader  [misc]` for the following class:

```py
from typing import Optional, Union, overload


class Transform:
    @overload
    def apply(self, b: bytes) -> bytes:
        """Return the transformed bytestring of the input"""

    @overload
    def apply(self, b: bytearray) -> None:
        """Transform the input bytearray in place"""

    def apply(self, b: Union[bytes, bytearray]) -> Optional[bytes]:
        pass
```

Changing the order of the two `@overload` doesn't give the error.

```
mypy --version
mypy 0.981 (compiled: yes)
```

**Comment by srittau** [comment]
Yes, `bytes` includes `bytearray` in argument types: https://docs.python.org/3/library/typing.html?highlight=typing#typing.ByteString.

**Comment by gsakkis** [comment]
So how is someone supposed to differentiate between the (actual) `bytes` vs `bytearray` types?
```py

def f(b: Union[bytes, bytearray]) -> None:
    if isinstance(b, bytes):
        print("bytes")
    else:
        print("bytearray")

f(bytearray())
```
Mypy claims `Statement is unreachable` for the `else` clause but it is clearly reachable.

**Comment by AlexWaygood** [comment]
You may be interested in [PEP 688](https://peps.python.org/pep-0688/) (written by @JelleZijlstra), which attempts to address this problem. The PEP is discussed here: https://discuss.python.org/t/pep-688-take-2-making-the-buffer-protocol-accessible-in-python/19756/1.

This problem was also recently discussed here: https://github.com/python/mypy/issues/12643.

Regardless, this isn't really a typeshed issue; there's nothing we can do about it in this repo :)
