### ISSUE TITLE
Should stubs contain default values?

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#8988]
This has come up recently, for similar reasons as #4881 and discussed a little there

From @gramster
> an advantage of including default values is that tools like pyright or pylance will use stubs (if available) for the signatures they show to users when hovering over a function call, and users want to see the default values. I'd like to understand your point of view though as to why you would prefer them removed?

I'm overall fine with this, though I'd like to see the following:
- we restrict it to simple literal values (e.g. anything that can go into a Literal)
- we can still use `...` at author's discretion (useful in overloads or cases where value doesn't actually matter or to avoid awful `x: Literal["x"] = "x"` things)
- we update e.g. stubtest to verify stuff

The case for:
- lets IDEs provide more information to users

The case against:
- most things are longer than `...` and terseness may be more valuable than the additional information
- it's a thing that needs doing and maintaining
- if we allow complicated default values there are more costs

A similar thing could apply to constants.

**Comment by JelleZijlstra** [comment]
I agree, a couple of small comments:

> * we restrict it to simple literal values (e.g. anything that can go into a Literal)

Other values that we could accept would include floats and types (e.g., for params like `dict_factory: Callable[..., ...] = dict`).

> * we can still use `...` at author's discretion (useful in overloads or cases where value doesn't actually matter or to avoid awful `x: Literal["x"] = "x"` things)
> * we update e.g. stubtest to verify stuff

It should be easy for stubtest to check defaults for correctness on Python functions (it's in the signature). For C functions, it's not necessarily possible to infer the default though, and indeed there may not be a default in a useful sense.

What other tools would need updating? I think we'd have to change flake8-pyi and hopefully nothing else.

**Comment by srittau** [comment]
It would be useful - but not necessary - to update stubgen as well.

**Comment by AlexWaygood** [comment]
I like the idea of adding simple default values to stubs. I agree that it's very useful in IDEs, and I think it'll be easier to maintain than adding docstrings to stubs.

The `= ...` convention that we currently use is nice because it keeps stubs as concise as possible. But... it looks _really weird_ to people who aren't used to it. I think it's nice for stubs to use the same syntax and conventions as normal Python wherever possible, and I remember finding the `= ...`s everywhere really strange and alien when I first started reading through typeshed's stubs.

> What other tools would need updating? I think we'd have to change flake8-pyi and hopefully nothing else.

Pyright also has a lint that enforces only using `...` as a default in stub files (ironically, since it's one of the IDEs that would benefit most from this change). We might be able to easily switch that off in our pyrightconfig file -- I'm not sure if it's bundled together with other stub-related lints or if it's a dedicated error code.

**Comment by sobolevn** [comment]
I have some concerns about it.

First of all, this will require more branching just for the sake of default values if it is different for different python versions.

Or we can show incorrect default values for this specific python version.

Secondly, default values are not a part of the signature. So, they can be changed in bugfix releases. It will make it much harder to maintain.

Next, stubs are even harder to maintain with default values.

Moreover, there are quite ugly defaults values like `_sentinel = object()` or others. Not sure we want this.

I think that IDEs can just use `inspect` to get the function and its defaults. It is much easier and it will always show correct results.

**Comment by AlexWaygood** [comment]
> Moreover, there are quite ugly defaults values like `_sentinel = object()` or others. Not sure we want this.

I like @hauntsaninja's proposal of only including "simple" defaults, e.g. "anything that's valid to go in a `Literal` slice". We can continue to use `...` for ugly or complex defaults.

**Comment by srittau** [comment]
I'll honestly expect 95% of all default values to be `None`.

**Comment by JelleZijlstra** [comment]
> First of all, this will require more branching just for the sake of default values if it is different for different python versions.

That will happen sometimes, but my sense is that it's not common.

> Secondly, default values are not a part of the signature. So, they can be changed in bugfix releases. It will make it much harder to maintain.

In theory, sure, but I'd be surprised if that happens with any frequency.

If maintainability concerns like these do come up frequently, we can revisit our decision, but I'd be surprised if it is a major issue. The stdlib doesn't change its defaults that much, and for third-party libraries we only support one version at a time.

**Comment by gramster** [comment]
I think that IDEs can just use inspect to get the function and its
defaults. It is much easier and it will always show correct results.

Easy in Jupyter with a running kernel; not as simple as it sounds in other
IDEs that may not be written in Python, need to be responsive, and don't
want to do a bunch of indexing up front.

**Comment by jpe** [comment]
IDEs will also probably want docstrings.

**Comment by JelleZijlstra** [comment]
Docstrings provide significantly more maintainability challenges. It's worth discussing whether it's worth changing our stance on docstrings too, but let's do that in a separate issue.

**Comment by AlexWaygood** [comment]
> IDEs will also probably want docstrings.

Please don't discuss docstrings here. We have the following issue for that discussion:

- #4881

**Comment by jpe** [comment]
Docstrings are relevant here because unless docstrings are also included, I think there's little benefit in including default values for IDEs. Those that want both will continue to need to merge signatures from .pyi, .py, and other files. I suspect that some might ignore default values from .pyi files because those from the .py file are probably more up to date. It would probably be a win for C implemented modules, though.

**Comment by Avasam** [comment]
Purely as a user, I really like when my IDE shows me default values of function parameters.
As a user of both libraries typed through Typeshed and inline-typed ones, I've noticed that's information lost in these third-party stubs, which is unfortunate.

I share the same feeling for #7258

Similarly to my comment here (https://github.com/python/typeshed/issues/4881#issuecomment-1275465471) and as gramster mentionned: Is this something editors could inspect when they come across `=...` ? (ie: fallback to the source python code, if available).

What's a good compromise between maintainability and not hiding information that would otherwise be available?

**Comment by JelleZijlstra** [comment]
It seems like there is agreement among the maintainers here, so I think we can move forward with changing our policy and allowing defaults. I wrote a little tool to help infer defaults from the runtime: https://github.com/JelleZijlstra/stubdefaulter. I can also work on adding support to stubtest for checking that defaults are right.

**Comment by Avasam** [comment]
https://github.com/microsoft/pyright/releases/tag/1.1.284
> Removed diagnostic check that detects a non-ellipsis default value in a stub file. This check was based on a now-outdated best practice. We now recommend that stubs include default values for better usability in language servers.

**Comment by AlexWaygood** [comment]
We've had great progress on this recently:
- [x] Pyright and flake8-pyi have both removed their lints forbidding stubs to have defaults
- [x] @JelleZijlstra's written a codemod to automatically insert defaults into stubs
- [x] @JelleZijlstra recently contributed a fix to pytype to prevent a crash if a stub has a string-literal as a default value
- [x] @JelleZijlstra contributed an enhancement to stubtest so that it verifies defaults in stubs are correct.

TODO, if anybody feels like taking these on:
- [ ] These docs need to be updated: https://github.com/python/typeshed/blob/2b9f200e7e111ab714217b7846b80538e875b472/CONTRIBUTING.md?plain=true#L450-L453. It's no longer true that "stub files should only contain information necessary for the type checker" -- they're also useful for IDEs. And, obviously, it's no longer true that default values should be omitted in all circumstances.
- [ ] Mypy's stubgen tool should be updated so that it no longer omits default values in all circumstances when generating stubs.

**Comment by Avasam** [comment]
Do you wanna use this issue to track running the codemod on existing stubs?

**Comment by JelleZijlstra** [comment]
My tool has a couple of problems, opened issues in https://github.com/JelleZijlstra/stubdefaulter. Hopefully I'll have time to work on those soon.

**Comment by AlexWaygood** [comment]
#9501 added a couple of defaults that are set to `sys.maxsize` at runtime, e.g.

https://github.com/python/typeshed/blob/7e40d70cad61d81a4db815911caa95440dae85f5/stdlib/collections/__init__.pyi#L166

The precise value of `sys.maxsize` will vary depending on what platform you're running Python on, so I think we should probably revert the changes where the default is set to `sys.maxsize` at runtime.

We could also consider adding a lint to flake8-pyi that forbids numeric defaults >6 digits (we can bikeshed the precise number of digits we want to permit) — thoughts?

**Comment by AlexWaygood** [comment]
Alternatively we could add some special-casing to flake8-pyi around `sys.maxsize` specifically, so that this is allowed in a stub:

```python
def count(self, sub: str | UserString, start: int = 0, end: int = sys.maxsize) -> int: ...
```

**Comment by JelleZijlstra** [comment]
Sorry for missing that! For now let's just remove those defaults.

`sys.maxsize` defaults are fairly common and intuitive, so it would be nice to be able to use them in stubs as in your above message. It would be good though to get user feedback (@gramster?) on what kind of more complex defaults would be usable and useful for IDEs.

**Comment by AlexWaygood** [comment]
In general I'm wary of allowing defaults that can't be easily verified by stubtest. I'd want most things that can't be easily verified by stubtest to be disallowed by flake8-pyi. But I'd be happy to special-case a small number of `ast.Attribute` nodes in flake8-pyi, and `sys.maxsize` seems like an obvious one to allow.

**Comment by AlexWaygood** [comment]
The default value here is set to `mmap.PAGESIZE` at runtime, which is `4096` on my machine, but evidently a much larger value on Jelle's machine:

https://github.com/python/typeshed/blob/7e40d70cad61d81a4db815911caa95440dae85f5/stdlib/multiprocessing/heap.pyi#L30

**Comment by AlexWaygood** [comment]
Here's a few funny ones I found using stubtest with mypy `master` 😄:

https://github.com/python/typeshed/blob/7e40d70cad61d81a4db815911caa95440dae85f5/stdlib/platform.pyi#L41

https://github.com/python/typeshed/blob/7e40d70cad61d81a4db815911caa95440dae85f5/stdlib/pydoc.pyi#L61

**Comment by Avasam** [comment]
I just found a nice side-effect of default parameter values:
```python
def foo(bar=None):...
# Is now equivalent to
def foo(bar: Incomplete | None = None): ...
```
But the former keeps "Unknown | None" in pyright and might be preferable.

**Comment by Avasam** [comment]
Is there anything left to do or discuss here? Seems like we're been adding defaults to parameters for a while.

**Comment by JelleZijlstra** [comment]
Alex's TODO list above says stubgen needs updating, but that's not something we can fix in this repo.

**Comment by Avasam** [comment]
> Alex's TODO list above says stubgen needs updating, but that's not something we can fix in this repo.

True, but as far as typeshed's concerned, I think https://github.com/python/typeshed/pull/10127  does the same until then 😃
