### ISSUE TITLE
shutil: copymode(), copystat() accept int arguments

### ISSUE THREAD

**Issue by mgorny** [python/typeshed#9288]
The `copymode()` and `copystat()` functions both accept file descriptors (i.e. `int` arguments) alternatively to paths. This isn't mentioned in shutil documentation but it is implied by the underlying `os` functions.

**Comment by ramvikrams** [comment]
@mgorny sir, I would like to work on this but I have a question, is it the documentation that has to be changed

**Comment by mgorny** [comment]
I don't know. If I knew, I'd have made a PR myself ;-).

**Comment by ramvikrams** [comment]
i'll it then

**Comment by AlexWaygood** [comment]
Issues about the CPython docs should be discussed at https://github.com/python/cpython/issues, not here. In typeshed, we generally prefer to follow the implementation, even if it is not explicitly documented.

**Comment by ramvikrams** [comment]
So should this issue be created in the cpython repo

**Comment by AlexWaygood** [comment]
> So should this issue be created in the cpython repo

No, because this issue isn't about the docs, it's about the type hints in https://github.com/python/typeshed/blob/main/stdlib/shutil.pyi. But if we want to discuss the docs, we should create another issue in the CPython repo, because that's a separate discussion.

**Comment by AlexWaygood** [comment]
It looks to me like `shutil.copymode()` will accept `int` arguments if `follow_symlinks` is `True` (the default), but will raise an exception if `follow_symlinks` is `False` and `int` arguments are passed in, since `shutil._islink` fails when `int`s are passed to it: https://github.com/python/cpython/blob/7bae15cf37239d4d345e09cc318bd82d03ec30cd/Lib/shutil.py#L298-L307.

That would imply that we should type the function like this:

```python
from _typeshed import StrOrBytesPath
from typing import overload
from typing_extensions import Literal

@overload
def copymode(src: StrOrBytesPath | int , dst: StrOrBytesPath | int, *, follow_symlinks: Literal[True] = ...) -> None: ...
@overload
def copymode(src: StrOrBytesPath, dst: StrOrBytesPath, *, follow_symlinks: bool) -> None: ...
```

The same goes for `copystat()`. It looks to me like this line will fail if `follow_symlinks` is set to `False` and an `int` is passed in: https://github.com/python/cpython/blob/7bae15cf37239d4d345e09cc318bd82d03ec30cd/Lib/shutil.py#L355.

@mgorny, thoughts?

**Comment by ramvikrams** [comment]
> @mgorny, thoughts?

I'll move forward after his thoughts

**Comment by mgorny** [comment]
That makes sense to me, though I already feel like I'm relying on undefined behavior :-(.

**Comment by JelleZijlstra** [comment]
This feels similar to python/cpython#90883, where various shutil functions accept or reject bytes paths under very specific circumstances depending on the exact code path being hit. Like in that case, I think we may be better off being stricter in typeshed until and unless CPython explicitly documents support for file descriptor parameters. If support for FDs isn't documented and tested in CPython, it's liable to break at any time.

**Comment by ramvikrams** [comment]
>```
> @overload
> def copymode(src: StrOrBytesPath, dst: StrOrBytesPath, *, follow_symlinks: Literal[False]) -> None: ...
> ```

 should I change the  false condition to Literal[False], as it would be better instead of bool.

**Comment by AlexWaygood** [comment]
I agree with @JelleZijlstra. In general, we prefer to follow the implementation rather than the documentation in typeshed. But this case just feels a bit too much like something that "happens to work" by accident,  where support could be accidentally removed in CPython at any time. It looks like @hauntsaninja also agrees, so I'm going to close this as "wontfix".

Thanks for the offer to make a PR, @ramvikrams — maybe next time :)

**Comment by ramvikrams** [comment]
> Thanks for the offer to make a PR, @ramvikrams — maybe next time :)
ya sure

**Comment by mgorny** [comment]
I've started https://discuss.python.org/t/is-it-valid-to-pass-fileno-to-shutil-copymode-copystat/21485 to discuss the problem on CPython end.
