### ISSUE TITLE
python-dateutil: should import submodules relativedelta, parser...

### ISSUE THREAD

**Issue by ilrico** [python/typeshed#9377]
quoted from a [pyright issue](https://github.com/microsoft/pyright/issues/3666) :  
"It looks like this might be a bug in the stub because the implementation actually does import (and re-export) relativedata via an `__all__` reference. (...) The `dateutil.__init__.pyi` stub would need to add statements like `from . import relativedelta` to indicate to type checkers that the submodule is automatically loaded by its parent module."

**Comment by AlexWaygood** [comment]
Thanks! #9381 should fix things.

**Comment by JelleZijlstra** [comment]
I think this may be a Pyright bug instead. `dateutil` does not, in fact, re-export its submodules:

```
% python           
iPython 3.11.0 (v3.11.0:deaf509e8f, Oct 24 2022, 14:43:23) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dateutil
>>> dateutil.parser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dateutil' has no attribute 'parser'
```

It *does* include them in `__all__`, which means that `from dateutil import *` will import the submodules. This is a somewhat strange behavior in the import system, so we may have to talk about how to handle it in the type system, but the proposed solution is incorrect.

**Comment by AlexWaygood** [comment]
Well that serves me right for reading the source code, but not checking at runtime.

It looks like the intention is to export them at runtime via the `__getattr__` method here: https://github.com/dateutil/dateutil/blob/b04edc08aa3559063b3b097f437941d8c4b84aba/src/dateutil/__init__.py#L12-L19. Not sure why they're not actually exported, but it's worth noting that they reorganised their module structure 2 days after the last release in July 2021. So that may have had an impact.

**Comment by JelleZijlstra** [comment]
`__init__.py` in the last release looks like this:

```python
try:
    from ._version import version as __version__
except ImportError:
    __version__ = 'unknown'

__all__ = ['easter', 'parser', 'relativedelta', 'rrule', 'tz',
           'utils', 'zoneinfo']
```

**Comment by AlexWaygood** [comment]
Okay, I'll close this for now, since I don't think there's anything actionable for us here.

In terms of the substantive issue being discussed, we already have #6523 open to discuss the same issue regarding weird `__all__`s in `__init__.py` files. In terms of fixing the immediate problem here, probably the best thing to do is to contact the upstream maintainers of `python-dateutil` and ask them to cut a new release; it looks like this may be fixed on the unreleased master branch.
