### ISSUE TITLE
Stubs for Greenlet

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#9493]
Greenlet is not typed and will require stubs for #9491
The maintainer(s) *"currently have no desire to try to maintain any typing information"*: https://github.com/python-greenlet/greenlet/issues/244)

**Comment by Avasam** [comment]
Alternatively, you you consider `sqlalchemy.util._concurrency_py3k.py__AsyncIoGreenlet` to be implementation details. Then a stub won't be needed.

**Comment by AlexWaygood** [comment]
> Alternatively, if you consider `sqlalchemy.util._concurrency_py3k.py__AsyncIoGreenlet` to be implementation details. Then a stub won't be needed.

It looks pretty implementation detail-y to me :)

Having said that, greenlet is quite a widely used package. Other people might also benefit from greenlet stubs. Up to you whether you think it's worth the effort or not!

**Comment by Avasam** [comment]
> Up to you whether you think it's worth the effort or not!

I'll leave this issue open (there's an existing need for this stub). But I'm probably gonna skip on being the one to add it for the time being :P

**Comment by AlexWaygood** [comment]
> I'll leave this issue open

Our general policy is to close issues like this, since there's not really anything actionable for the maintainers, and issues like this tend to accumulate and grow stale pretty quickly if we don't close them 😉

For anybody else reading this: feel free to contribute stubs to greenlet at any time! PRs are always welcome.
