### ISSUE TITLE
python-dateutil: expose relativedelata.weekday type

### ISSUE THREAD

**Issue by eltoder** [python/typeshed#9817]
It would be good to expose the type of the weekday constants (MO, TU, ...) internally known as `weekday`. Otherwise it's hard to type functions and variables that use it. For example:
```python
from dateutil import relativedelta

class Calendar:
    def __init__(self, week_start: X = relativedelta.MO) -> None:
        self.week_start = week_start
```
What type should go in instead of `X`?

**Comment by AlexWaygood** [comment]
We usually try to avoid adding re-exports in the stubs unless it seems like the re-exports were intentional at runtime (e.g. in an `__init__.py` file for a package) rather than just an implementation detail. But the use case here seems reasonable, since the `weekday` class isn't exposed publicly anywhere else, and since stubtest will alert us if the import is removed at runtime. I'll send a PR.

**Comment by AlexWaygood** [comment]
A new version of `types-python-dateutil` will be autouploaded to PyPI at some point in the next few hours. With the latest version of the package, you'll be able to do this:

```python
from dateutil import relativedelta

class Calendar:
    def __init__(self, week_start: relativedelta.weekday = relativedelta.MO) -> None:
        self.week_start = week_start
```

**Comment by eltoder** [comment]
Thank you!
